### ISSUE TITLE
403 error code for `Shouldly` package

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#1017]
```
Downloading Shouldly 2.5.0 to ..\AppData\Local\NuGet\Cache\Shouldly.2.5.0.nupkg
[13:19:55]W:	 [Step 2/2] Paket failed with:
[13:19:55]W:	 [Step 2/2] 	Could not download Shouldly 2.5.0.
[13:19:55]W:	 [Step 2/2]     The remote server returned an error: (403) Forbidden.
```

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/9519083/0661e248-4cbc-11e5-80c7-658ff6f4ba70.png)

I can't repro. Any ideas what I need to do?

**Comment by vasily-kirichenko** [comment]
Shouldly is a new package in the branch. I went to the TC agent server and deleted ExtCore package, result:
```
d:\BuildAgent\work\2879dffe5c203564>.paket\paket restore
Paket version 1.33.1.0
ExtCore 0.8.45 unzipped to d:\BuildAgent\work\2879dffe5c203564\packages\ExtCore
Downloading Shouldly 2.5.0 to C:\Users\...\AppData\Local\NuGet\Cach
e\Shouldly.2.5.0.nupkg
Something went wrong with the download of Shouldly 2.5.0 - automatic retry with
--force.
Downloading Shouldly 2.5.0 to C:\Users\...\AppData\Local\NuGet\Cach
e\Shouldly.2.5.0.nupkg
Paket failed with:
        Could not download Shouldly 2.5.0.
    The remote server returned an error: (403) Forbidden.
```

**Comment by vasily-kirichenko** [comment]
Reliably reproduced on 3 servers.

**Comment by vasily-kirichenko** [comment]
```
No .targets files found in d:\BuildAgent\work\2879dffe5c203564\packages\System.Spatial
loaded details for 'Shouldly@2.5.0' from url 'https://www.nuget.org/api/v2'
License for Shouldly 2.5.0 already downloaded
Downloading Shouldly 2.5.0 to C:\Users\...\AppData\Local\NuGet\Cache\Shouldly.2.5.0.nupkg
Something went wrong with the download of Shouldly 2.5.0 - automatic retry with --force.
Response from https://www.nuget.org/api/v2/Packages?$filter=Id eq 'Shouldly' and NormalizedVersion eq '2.5.0':

<?xml version="1.0" encoding="utf-8"?><feed xml:base="https://www.nuget.org/api/v2/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><id>https://www.nuget.org/api/v2/Packages</id><title type="text">Packages</title><updated>2015-08-27T11:25:56Z</updated><link rel="self" title="Packages" href="Packages" /><entry><id>https://www.nuget.org/api/v2/Packages(Id='Shouldly',Version='2.5.0')</id><category term="NuGetGallery.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" title="V2FeedPackage" href="Packages(Id='Shouldly',Version='2.5.0')" /><title type="text">Shouldly</title><summary type="text"></summary><updated>2015-08-26T07:52:26Z</updated><author><name>Dave Newman,  Xerxes Battiwalla,  Anthony Egerton,  Peter van der Woude,  Jake Ginnivan</name></author><link rel="edit-media" title="V2FeedPackage" href="Packages(Id='Shouldly',Version='2.5.0')/$value" /><content type="application/zip" src="https://www.nuget.org/api/v2/package/Shouldly/2.5.0" /><m:properties><d:Version>2.5.0</d:Version><d:NormalizedVersion>2.5.0</d:NormalizedVersion><d:Copyright m:null="true" /><d:Created m:type="Edm.DateTime">2015-04-12T16:48:12.627</d:Created><d:Dependencies></d:Dependencies><d:Description>Shouldly - Assertion framework for .NET. The way asserting *Should* be</d:Description><d:DownloadCount m:type="Edm.Int32">88339</d:DownloadCount><d:GalleryDetailsUrl>https://www.nuget.org/packages/Shouldly/2.5.0</d:GalleryDetailsUrl><d:IconUrl>https://raw.github.com/shouldly/shouldly/master/Icons/package_icon.png</d:IconUrl><d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion><d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion><d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease><d:Language m:null="true" /><d:Published m:type="Edm.DateTime">2015-04-12T16:48:12.627</d:Published><d:PackageHash>oGH4OL3Y04hwPiFjeQaTqZq2qtzeZozGjmS/cEQU1RlU5TgZns68pDtf9Kmxq+swnB+2btVbaFs2xRgWfxfvSg==</d:PackageHash><d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm><d:PackageSize m:type="Edm.Int64">265344</d:PackageSize><d:ProjectUrl>http://shouldly.github.com/</d:ProjectUrl><d:ReportAbuseUrl>https://www.nuget.org/package/ReportAbuse/Shouldly/2.5.0</d:ReportAbuseUrl><d:ReleaseNotes>- task.ShouldCompleteIn(Timeout)
- task.ShouldThrow now times out after 10 second, specify timeout or use ShouldlyConfiguration.DefaultTaskTimeout to change</d:ReleaseNotes><d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance><d:Summary m:null="true" /><d:Tags>testing unit TDD AAA shoulda testunit rspec</d:Tags><d:Title m:null="true" /><d:VersionDownloadCount m:type="Edm.Int32">13559</d:VersionDownloadCount><d:MinClientVersion m:null="true" /><d:LastEdited m:type="Edm.DateTime" m:null="true" /><d:LicenseUrl>https://github.com/shouldly/shouldly/blob/master/LICENSE.txt</d:LicenseUrl><d:LicenseNames m:null="true" /><d:LicenseReportUrl m:null="true" /></m:properties></entry></feed>
loaded details for 'Shouldly@2.5.0' from url 'https://www.nuget.org/api/v2'
Downloading Shouldly 2.5.0 to C:\Users\svc_klsrl.tester\AppData\Local\NuGet\Cache\Shouldly.2.5.0.nupkg
Downloading license for Shouldly 2.5.0 to C:\Users\svc_klsrl.tester\AppData\Local\NuGet\Cache\Shouldly.2.5.0.license.html

Paket failed with:
        Could not download Shouldly 2.5.0.
    The remote server returned an error: (403) Forbidden.
StackTrace:
     at Paket.NuGetV2.DownloadPackage@559-31.Invoke(String message)
   at Paket.NuGetV2.DownloadPackage@514-30.Invoke(Exception _arg11)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Paket.RestoreProcess.Restore(String dependenciesFileName, Boolean force, FSharpList`1 referencesFileNames)
   at <StartupCode$Paket-Core>.$PublicAPI.Restore@209-1.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Program.handler@288-13.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   at Paket.Program.processCommand@66-1.Invoke(Command command, String[] args)
   at Paket.Program.main()
```

**Comment by vasily-kirichenko** [comment]
It would be good if paket shows full URL where it downloading packages from.

**Comment by forki** [comment]
@maartenba do you know why 403 might happen?

**Comment by maartenba** [comment]
Which was the URL that returned 403?

**Comment by vasily-kirichenko** [comment]
```
Paket version 1.33.2.0
...
No .targets files found in d:\BuildAgent\work\2879dffe5c203564\packages\System.Spatial
loaded details for 'Shouldly@2.5.0' from url 'https://www.nuget.org/api/v2'
Downloading Shouldly 2.5.0 to C:\Users\...\AppData\Local\NuGet\Cache\Shouldly.2.5.0.nupkg
Something went wrong with the download of Shouldly 2.5.0 - automatic retry with --force.
Response from https://www.nuget.org/api/v2/Packages?$filter=Id eq 'Shouldly' and NormalizedVersion eq '2.5.0':

<?xml version="1.0" encoding="utf-8"?><feed xml:base="https://www.nuget.org/api/v2/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><id>https://www.nuget.org/api/v2/Packages</id><title type="text">Packages</title><updated>2015-08-27T11:53:49Z</updated><link rel="self" title="Packages" href="Packages" /><entry><id>https://www.nuget.org/api/v2/Packages(Id='Shouldly',Version='2.5.0')</id><category term="NuGetGallery.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" title="V2FeedPackage" href="Packages(Id='Shouldly',Version='2.5.0')" /><title type="text">Shouldly</title><summary type="text"></summary><updated>2015-08-26T07:52:26Z</updated><author><name>Dave Newman,  Xerxes Battiwalla,  Anthony Egerton,  Peter van der Woude,  Jake Ginnivan</name></author><link rel="edit-media" title="V2FeedPackage" href="Packages(Id='Shouldly',Version='2.5.0')/$value" /><content type="application/zip" src="https://www.nuget.org/api/v2/package/Shouldly/2.5.0" /><m:properties><d:Version>2.5.0</d:Version><d:NormalizedVersion>2.5.0</d:NormalizedVersion><d:Copyright m:null="true" /><d:Created m:type="Edm.DateTime">2015-04-12T16:48:12.627</d:Created><d:Dependencies></d:Dependencies><d:Description>Shouldly - Assertion framework for .NET. The way asserting *Should* be</d:Description><d:DownloadCount m:type="Edm.Int32">88353</d:DownloadCount><d:GalleryDetailsUrl>https://www.nuget.org/packages/Shouldly/2.5.0</d:GalleryDetailsUrl><d:IconUrl>https://raw.github.com/shouldly/shouldly/master/Icons/package_icon.png</d:IconUrl><d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion><d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion><d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease><d:Language m:null="true" /><d:Published m:type="Edm.DateTime">2015-04-12T16:48:12.627</d:Published><d:PackageHash>oGH4OL3Y04hwPiFjeQaTqZq2qtzeZozGjmS/cEQU1RlU5TgZns68pDtf9Kmxq+swnB+2btVbaFs2xRgWfxfvSg==</d:PackageHash><d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm><d:PackageSize m:type="Edm.Int64">265344</d:PackageSize><d:ProjectUrl>http://shouldly.github.com/</d:ProjectUrl><d:ReportAbuseUrl>https://www.nuget.org/package/ReportAbuse/Shouldly/2.5.0</d:ReportAbuseUrl><d:ReleaseNotes>- task.ShouldCompleteIn(Timeout)
- task.ShouldThrow now times out after 10 second, specify timeout or use ShouldlyConfiguration.DefaultTaskTimeout to change</d:ReleaseNotes><d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance><d:Summary m:null="true" /><d:Tags>testing unit TDD AAA shoulda testunit rspec</d:Tags><d:Title m:null="true" /><d:VersionDownloadCount m:type="Edm.Int32">13569</d:VersionDownloadCount><d:MinClientVersion m:null="true" /><d:LastEdited m:type="Edm.DateTime" m:null="true" /><d:LicenseUrl>https://github.com/shouldly/shouldly/blob/master/LICENSE.txt</d:LicenseUrl><d:LicenseNames m:null="true" /><d:LicenseReportUrl m:null="true" /></m:properties></entry></feed>
loaded details for 'Shouldly@2.5.0' from url 'https://www.nuget.org/api/v2'
Downloading Shouldly 2.5.0 to C:\Users\...\AppData\Local\NuGet\Cache\Shouldly.2.5.0.nupkg
```

**Comment by maartenba** [comment]
@forki which would be the URL that was attempted from this log?

**Comment by forki** [comment]
something is fucky. I disabled the license file download for now. Maybe now you can see the error message?

**Comment by vasily-kirichenko** [comment]
```
d:\BuildAgent\work\2879dffe5c203564>.paket\paket restore
Paket version 1.33.3.0
Downloading Shouldly 2.5.0 to C:\Users\...\AppData\Local\NuGet\Cache\Shouldly.2.5.0.nupkg
Something went wrong with the download of Shouldly 2.5.0 - automatic retry with --force.
Downloading Shouldly 2.5.0 to C:\Users\...\AppData\Local\NuGet\Cache\Shouldly.2.5.0.nupkg
Paket failed with:
        Could not download Shouldly 2.5.0 from https://www.nuget.org/api/v2/package/Shouldly/2.5.0.
    The remote server returned an error: (403) Forbidden.
```

**Comment by forki** [comment]
ok, that url works for me

**Comment by vasily-kirichenko** [comment]
The trailing dot in `https://www.nuget.org/api/v2/package/Shouldly/2.5.0.` looks very suspicious.

**Comment by vasily-kirichenko** [comment]
![image](https://cloud.githubusercontent.com/assets/873919/9520532/c2f46c00-4cd0-11e5-97ad-b874a35d6d50.png)

**Comment by maartenba** [comment]
`200 OK - https://www.nuget.org/api/v2/package/Shouldly/2.5.0`
`500 Internal Server Terror - https://www.nuget.org/api/v2/package/Shouldly/2.5.0.`

**Comment by vasily-kirichenko** [comment]
@maartenba yep.

**Comment by forki** [comment]
I see. Let's try to find out where this is coming from.
Give me a minute.

**Comment by vasily-kirichenko** [comment]
![1](https://cloud.githubusercontent.com/assets/873919/9520574/020d349e-4cd1-11e5-8a2f-d5de704c37b0.gif)

**Comment by forki** [comment]
I can't read russian? what does the video tell me? ;-)

**Comment by vasily-kirichenko** [comment]
"The web page is unreached" or something like this :)

**Comment by vasily-kirichenko** [comment]
I think that's a different problem, maybe paket can download it.

**Comment by forki** [comment]
that is really strange. we extract that url from the OData result.

**Comment by maartenba** [comment]
@forki Just thought of something. By any chance, is an Authorization header sent to the CDN URL? If so - don't (it's a different domain so credentials should not be valid on there). The underlying Azure Storage returns a 403 in those cases.

**Comment by forki** [comment]
[https://nuget.org/api/v2/Packages?$filter=Id eq 'Shouldly' and NormalizedVersion eq '2.5.0'] is what we query

**Comment by maartenba** [comment]
No `.` in the result of that call. Check my previous comment on auth, I suspect it's that.

**Comment by vasily-kirichenko** [comment]
@forki Does not add a trailing dot when outputs "Could not download Shouldly 2.5.0 from https://www.nuget.org/api/v2/package/Shouldly/2.5.0."?

**Comment by forki** [comment]
ha yes. it's part of the error message

**Comment by forki** [comment]
so the real issue is that you get 403 for https://www.nuget.org/api/v2/package/Shouldly/2.5.0 - even in your chrome.

**Comment by forki** [comment]
@maartenba https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/NuGetV2.fs#L521 <- this where we handle auth.

Since auth = None we set UseDefaultCredentials to true.

**Comment by maartenba** [comment]
Fiddler gives me a nice `200 OK`. I suspect credentials are somehow being sent here.

**Comment by forki** [comment]
@maartenba but @vasily-kirichenko can't even reach it from browser.

**Comment by maartenba** [comment]
@vasily-kirichenko Can you try https://www.nuget.org/users/account/LogOff?returnUrl=%2F ? Check stored credentials in Windows?

**Comment by maartenba** [comment]
Also "can't reach" was with the `.` URL. I bet the non-`.` one just works :tm:

**Comment by vasily-kirichenko** [comment]
I pointed my browser to https://www.nuget.org/api/v2/package/Shouldly/2.5.0 and after 30 seconds it redirects me to https://www.nuget.org/

**Comment by vasily-kirichenko** [comment]
Now it redirects to https://az320820.vo.msecnd.net/packages/shouldly.2.5.0.nupkg, then show "ERR_CONNECTION_REFUSED" error.

**Comment by maartenba** [comment]
@vasily-kirichenko Can you give it another try? I flushed the CDN for that URL.

**Comment by vasily-kirichenko** [comment]
Paket failed with:
        Could not download Shouldly 2.5.0 from https://www.nuget.org/api/v2/pack
age/Shouldly/2.5.0.
    The remote server returned an error: (403) Forbidden.

**Comment by maartenba** [comment]
Can you try this with Fiddler/curl/any other tool that is close to the wire?

**Comment by vasily-kirichenko** [comment]
```
d:\BuildAgent\work\2879dffe5c203564>curl https://www.nuget.org/api/v2/package/Shouldly/2.5.0 -v
*   Trying 191.236.146.247...
* connect to 191.236.146.247 port 443 failed: Connection refused
* Failed to connect to www.nuget.org port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to www.nuget.org port 443: Connection refused
```

**Comment by maartenba** [comment]
Looks like a connection issue. Can the build machine connect to the Internet?

**Comment by vasily-kirichenko** [comment]
Yes, it can open pages in a browser (which uses system proxy settings).

**Comment by vasily-kirichenko** [comment]
On my machine:

![image](https://cloud.githubusercontent.com/assets/873919/9521799/a66801d8-4cd9-11e5-9591-b8a48515e8f1.png)

**Comment by vasily-kirichenko** [comment]
Could you guys try to add a some new for you package via VS UI?

**Comment by maartenba** [comment]
I _seriously_ suspect a client-side config issue here, which may well be related to the proxy.

**Comment by vasily-kirichenko** [comment]
It was a local problem, sorry for disturbing.

**Comment by forki** [comment]
No worries. And big thanks to Maarten for helping again. Kudos!
