### ISSUE TITLE
Paket fails to get package versions (2.1.0 - 2.3.4)

### ISSUE THREAD

**Issue by MiloszKrajewski** [fsprojects/Paket#1079]
paket outdated fails with:

```
Could not find versions for package DotNetZip.Reduced in any of the sources in [Nuget {Url = "https://www.nuget.org/api/v2"; Authentication = null;}].
```

Thank to paket.bootstrapper I was able to check out multiple versions. So it works fine up to 2.0.3, then starts to fail at 2.1.0 up to 2.3.4 (the most recent version at the time I'm writing this). It might be important that I am behind proxy but even then the older version works.

```
PS D:\prj\external\lz4net\src> .\paket.cmd outdated --verbose
No version specified. Downloading latest stable.
Paket.exe 2.3.4.0 is up to date.
Paket version 2.3.4.0
found: D:\prj\external\lz4net\src\paket.dependencies
Parsing D:\prj\external\lz4net\src\paket.dependencies
Resolving packages for group Main:
  0 packages in resolution. 4 requirements left
  Trying to resolve DotNetZip.Reduced  (from D:\prj\external\lz4net\src\paket.dependencies)
  - fetching versions for DotNetZip.Reduced
getAllVersionsFromNuGet2 from url 'https://www.nuget.org/api/v2/package-versions/DotNetZip.Reduced?includePrerelease=true'
getAllVersionsFromNugetOData from url 'https://www.nuget.org/api/v2/FindPackagesById()?id='DotNetZip.Reduced''
getAllVersionsFromNugetODataWithFilter from url 'https://www.nuget.org/api/v2/Packages?$filter=Id eq 'DotNetZip.Reduced''
Paket failed with:
        Could not find versions for package DotNetZip.Reduced in any of the sources in [Nuget {Url = "https://www.nuget.org/api/v2";
        Authentication = null;}].
StackTrace:
     at Paket.NuGetV2.GetVersions@651.Invoke(String message)
   at Paket.NuGetV2.GetVersions(String root, IEnumerable`1 sources, PackageName _arg1)
   at Paket.PackageResolver.getAllVersions@235(FSharpFunc`2 getVersionsF, Dictionary`2 allVersions, FSharpList`1 sources, PackageName packageName, VersionRange vr)
   at Paket.PackageResolver.step$cont@298(FSharpSet`1 requirements, FSharpFunc`2 getVersionsF, Dictionary`2 allVersions, PackageRequirement currentRequirement, FSharpRef`1 availableVersions, FSharpRef`1 compatibleVersions, FSharpRef`1 globalOverride, FSharpList`1 currentRequirements, Unit unitVar)
   at Paket.PackageResolver.step@249(FSharpSet`1 requirements, FSharpList`1 globalFrameworkRestrictions, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, Dictionary`2 exploredPackages, Dictionary`2 allVersions, Dictionary`2 conflictHistory, FSharpMap`2 filteredVersions, FSharpList`1 selectedPackageVersions, FSharpSet`1 closedRequirements, FSharpSet`1 openRequirements)
   at Paket.PackageResolver.Resolve(GroupName groupName, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, FSharpList`1 globalFrameworkRestrictions, FSharpList`1 rootDependencies, FSharpSet`1 requirements)
   at <StartupCode$Paket-Core>.$DependenciesFile.Resolve@410-2.Invoke(GroupName k, RequirementsGroup group)
   at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
   at Microsoft.FSharp.Collections.FSharpMap`2.Map[b](FSharpFunc`2 f)
   at Paket.FindOutdated.FindOutdated@34.Invoke(LockFile _arg1)
   at Chessie.ErrorHandling.Trial.fSuccess@63-11[p,r,q](FSharpFunc`2 f, p x, FSharpList`1 msgs)
   at Paket.FindOutdated.ShowOutdated(Boolean strict, Boolean includingPrereleases, PaketEnv environment)
   at <StartupCode$Paket-Core>.$PublicAPI.fSuccess@63-25[a](FSharpFunc`2 f, PaketEnv x, FSharpList`1 msgs)
   at Paket.Dependencies.Process[a](FSharpFunc`2 f)
   at Paket.Program.handler@296-11.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   at Paket.Program.processCommand@66-1.Invoke(Command command, String[] args)
   at Paket.Program.main()
```

while older version works fine:

```
PS D:\prj\external\lz4net\src> .\paket.cmd outdated
Version 2.0.3 requested.
Paket.exe 2.0.3.0 is up to date.
Paket version 2.0.3.0
Resolving packages for group Main:
 - DotNetZip.Reduced 1.9.1.8
 - FAKE 4.4.4
 - LibZ.Bootstrap 1.1.0.2
 - NUnit 2.6.4
No outdated packages found.
3 seconds - ready.
```

**Comment by forki** [comment]
so this seems to be a side-effect of https://github.com/fsprojects/Paket/pull/1061
@dedale could you please take a look?

**Comment by forki** [comment]
https://github.com/fsprojects/Paket/commit/0792bedeb0c1a38a85faced7c2ff7b9aea25f65b#diff-4d7cd68c6813f092c784e32c518577e6R126 seems to be the change that causes this to break.

**Comment by dedale** [comment]
@MiloszKrajewski do you use http_proxy and https_proxy env variables? 
@forki I spotted a bug this morning : creating a WebProxy with an https Uri fails, this is not supported. So I must hard-code scheme as http. Unfortunately I cannot push from work.

**Comment by forki** [comment]
Can you email me the patch?

**Comment by dedale** [comment]
Finally found a way to push a PR with the fix for the bug I spotted. Hope
it solves #1079.

**Comment by forki** [comment]
@MiloszKrajewski could you please try 2.3.6?

**Comment by MiloszKrajewski** [comment]
@dedale Yup. Using both HTTP_PROXY and HTTPS_PROXY.
@forki 2.3.6 fixes the problem. Thanks.

**Comment by forki** [comment]
Awesome!

2015-09-22 14:16 GMT+02:00 Milosz Krajewski <notifications@github.com>:

**Comment by dedale** [comment]
:relieved:
