### ISSUE TITLE
KeyNotFoundException when project is net4.0-client

### ISSUE THREAD

**Issue by Stift** [fsprojects/Paket#1095]
We have a project that has in its csproj file the following settings
`<TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
<TargetFrameworkProfile>Client</TargetFrameworkProfile>`

`paket install --verbose` fails with the following exception and stacktrace
```
Paket failed with:
        Exception of type 'System.Collections.Generic.KeyNotFoundException' was thrown.
StackTrace:
     at Microsoft.FSharp.Collections.ListModule.Pick[T,TResult](FSharpFunc`2 chooser, FSharpList`1 list)
   at Paket.BindingRedirects.applyBindingRedirects(FSharpFunc`2 bindingRedirects, String configFilePath)
   at Paket.BindingRedirects.applyBindingRedirectsToFolder@148-3.Invoke(String configFilePath)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at Paket.InstallProcess.InstallIntoProjects(InstallerOptions options, DependenciesFile dependenciesFile, LockFile lockFile, FSharpList`1 projects)
   at <StartupCode$Paket-Core>.$PublicAPI.Install@148.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Program.handler@295-10.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   at Paket.Program.processCommand@66-1.Invoke(Command command, String[] args)
   at Paket.Program.main()
```
I was able to break this issue down to https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/FrameworkHandling.fs#l360 where is no PortableProfile with a 'Client' definition.
I hope I provided the right information to solve this issue, else I'm open for questions.

**Comment by forki** [comment]
mhm. not sure I understand the issue. can you provide me a repro sample?

**Comment by Stift** [comment]
mmh. Thought I explained it good enough. Find in the linked zip file everything you need to replay this
[Link](https://www.dropbox.com/s/pizh76jiuz2v53q/PaketBugSample.zip?dl=0).
As I said before I debugged to the point that it crashes at the point mentioned above when it tries to find a match for TargetFrameworkProfile.

**Comment by forki** [comment]
Your instructions were good, but I didn't really see the root cause and I
assume a repro will help

**Comment by forki** [comment]
thanks for the repro. I now understand much better ;-)

**Comment by Stift** [comment]
Works very fine.
![](http://i.giphy.com/sXR1LMCu1zZm.gif)
