### ISSUE TITLE
Give better error message when a file can't be found on a github repo

### ISSUE THREAD

**Issue by Thorium** [fsprojects/Paket#1162]
paket.dependencies:

    source https://www.nuget.org/api/v2

    github lodash/lodash lodash.min.js

Response:

C:\myTest>.paket\paket.exe install --verbose
Paket version 2.8.0.0
found: C:\myTest\paket.dependencies
Parsing C:\myTest\paket.dependencies
Resolving packages for group Main:
Locked version resolution written to C:\myTest\paket.lock
Downloading lodash/lodash:d5f51f288121971a06802ad783179f9304ec5093 lodash.min.js to C:\myTest\paket-files\lodash\lodash\lodash.min.js
Paket failed with:
        Could not download from https://raw.githubusercontent.com/lodash/lodash/d5f51f288121971a06802ad783179f9304ec5093/lodash.min.js
 Message: One or more errors occurred.
StackTrace:
     at Paket.Utils.downloadFromUrl@215-5.Invoke(String message)
   at Paket.Utils.downloadFromUrl@208-4.Invoke(Exception _arg3)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Paket.InstallProcess.createModel(String root, Boolean force, DependenciesFile dependenciesFile, LockFile lockFile, FSharpSet`1 packages)
   at Paket.InstallProcess.InstallIntoProjects(InstallerOptions options, DependenciesFile dependenciesFile, LockFile lockFile, FSharpList`1 projects)
   at <StartupCode$Paket-Core>.$PublicAPI.Install@148.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Program.handler@290-10.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   at Paket.Program.processCommand@61-1.Invoke(Command command, String[] args)
   at Paket.Program.main()

**Comment by forki** [comment]
where is the correct resource? where do you expect paket to download that file?

**Comment by forki** [comment]
If I look at https://github.com/lodash/lodash/ then there is no lodash.min.js in the root

**Comment by forki** [comment]
lol https://github.com/lodash/lodash/commit/d5f51f288121971a06802ad783179f9304ec5093 removed that file ;-)

**Comment by forki** [comment]
So in this case there is nothing we can do, but to give a good error message.

**Comment by Thorium** [comment]
Ok thanks, didn't expect that! :-D

**Comment by forki** [comment]
it will now show the 404:

![image](https://cloud.githubusercontent.com/assets/57396/10695319/6d197dca-79a3-11e5-915d-91285acd4d76.png)
