### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#1256]
* erase a package version number in `paket.lock`
* run `paket install`
```
L:\hg\klsrl.core>.paket\paket.exe install -v
Paket version 2.23.4.0
found: L:\hg\klsrl.core\paket.dependencies
Parsing L:\hg\klsrl.core\paket.dependencies
Paket failed with:
        Index was outside the bounds of the array.
StackTrace:
     at Paket.LockFileParser.Parse$cont@255(FSharpFunc`2 removeBrackets, String line, FSharpList`1 otherGroups, ParseState currentGroup, Uni
t unitVar)
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at Paket.LockFile.Parse(String lockFileName, String[] lines)
   at Paket.UpdateProcess.SelectiveUpdate(DependenciesFile dependenciesFile, UpdateMode updateMode, SemVerUpdateMode semVerUpdateMode, Boole
an force)
   at Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions options)
   at <StartupCode$Paket-Core>.$PublicAPI.Install@155.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Program.handler@337-10.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   at Paket.Program.processCommand@61-1.Invoke(Command command, String[] args)
   at Paket.Program.main()
```

**Comment by forki** [comment]
Why would you change the lock file manually?
