### ISSUE TITLE
2.36.2 - Null Reference Exception

### ISSUE THREAD

**Issue by harrisonmeister** [fsprojects/Paket#1309]
Hi I have just downloaded 2.36.2 using the bootstrapper as part of a build process and receive the following error:

Paket version 2.36.2.0
No platform specified; found output path node for the AnyCPU platform after failing to find one for the following:

 (the above error is repeated a number of times)

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Paket.PackageMetaData.loadAssemblyAttributes@95-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.PackageMetaData.loadAssemblyAttributes@92.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.PackageProcess.merge$cont@21(String buildConfig, String buildPlatform, ProjectFile projectFile, TemplateFile templateFile, TemplateFile withVersion, Unit unitVar)
   at Paket.PackageProcess.f@1-13(String buildConfig, String buildPlatform, FSharpOption`1 version, HashSet`1 allTemplateFiles, ProjectFile projectFile, TemplateFile templateFile)
   at Paket.PackageProcess.Pack[a](String workingDir, DependenciesFile dependencies, String packageOutputPath, FSharpOption`1 buildConfig, FSharpOption`1 buildPlatform, FSharpOption`1 version, FSharpOption`1 releaseNotes, FSharpOption`1 templateFile, FSharpOption`1 excludedTemplates, Boolean lockDependencies, Boolean symbols)
   at Paket.Program.handler@350-20.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   at Paket.Program.processCommand@61-1.Invoke(Command command, String[] args)
   at Paket.Program.main()
   at <StartupCode$paket>.$Paket.Program.main@()

I have pinned my build to release 2.35.0 for now, but wanted to let you know

Thanks, Mark

**Comment by forki** [comment]
duplicate as #1307 - fixed in #1308 
Please try Paket 2.36.5 and let me know.
Thanks for reporting
