### ISSUE TITLE
Variables in ProjectReference include attribute should be parsed

### ISSUE THREAD

**Issue by ErwinSteffens** [fsprojects/Paket#1377]
Paket should parse macro's/variables in the ProjectReference include attribute used. We have the following include path which is not accepted by Paket:

```
<ProjectReference Include="$(SolutionDir)Subfolder\MyProject\MyProject.csproj">
    <Project>{b5ff0cfe-5699-4b6e-922a-e1f5ea5f948d}</Project>
    <Name>MyProject</Name>
</ProjectReference>
```

Paket gives the following error when parsing the csproj file:
```
Unable to parse C:\MySolution\Project1\$(SolutionDir)Subfolder\MyProject\MyProject.csproj:
      Could not find a part of the path 'C:\MySolution\Project1\$(SolutionDir)Subfolder\MyProject\MyProject.csproj'.
```

For us it is good enough to just resolve the SolutionDir only. When accepted we can try to fix it ourself. Is there already a method which resolves macro's/variables available within the Paket source?

**Comment by forki** [comment]
can you please run the same command with -v and give the full error message?

**Comment by ErwinSteffens** [comment]
I can include the full log, but I think this is the most important path:

```
Installing to C:\Work\ManagedCodeGit\CrossPoint.Service.CrossConnectServer\CrossPoint.Service.CrossConnectServerProxy\CrossPoint.Library.CrossConnectServerProxy.csproj
    - Deleting Paket Reference nodes
Unable to parse C:\Work\ManagedCodeGit\CrossPoint.Service.CrossConnectServer\CrossPoint.Database\CrossPoint.Database\$(SolutionDir)CrossPoint.Library.Core\CrossPoint.Framework\CrossPoint.Framework.csproj:
      Could not find a part of the path 'C:\Work\ManagedCodeGit\CrossPoint.Service.CrossConnectServer\CrossPoint.Database\CrossPoint.Database\$(SolutionDir)CrossPoint.Library.Core\CrossPoint.Framework\CrossPoint.Framework.csproj'.
Unable to parse C:\Work\ManagedCodeGit\CrossPoint.Service.CrossConnectServer\CrossPoint.Database\CrossPoint.Library.Core\CrossPoint.Framework\CrossPoint.Framework.csproj:
      Could not find a part of the path 'C:\Work\ManagedCodeGit\CrossPoint.Service.CrossConnectServer\CrossPoint.Database\CrossPoint.Library.Core\CrossPoint.Framework\CrossPoint.Framework.csproj'.
```

**Comment by forki** [comment]
I was interested in the call stack from where this error is thrown.

**Comment by ErwinSteffens** [comment]
It does not give a stacktrace, only the exception message. This method fails in the ProjectFile.fs on line 1116:

```
static member TryLoad(fileName:string) =
    try
        Some(ProjectFile.LoadFromFile(fileName))
    with
    | exn -> 
        traceWarnfn "Unable to parse %s:%s      %s" fileName Environment.NewLine exn.Message
        None
```

**Comment by ErwinSteffens** [comment]
Here is stacktrace:

```
      System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Work\ManagedCodeGit\CrossPoint.Database\CrossPoint.DataAccess\$(SolutionDir)CrossPoint.DataAccess.Database\CrossPoint.DataAccess.Database.csproj'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileInfo.OpenRead()
   at Paket.ProjectFile.LoadFromFile(String fileName) in C:\Probeer\Paket\src\Paket.Core\ProjectFile.fs:line 1113
   at Paket.ProjectFile.TryLoad(String fileName) in C:\Probeer\Paket\src\Paket.Core\ProjectFile.fs:line 1118
```

**Comment by forki** [comment]
please try with 2.42.4
