### ISSUE TITLE
Errors when building

### ISSUE THREAD

**Issue by pms1969** [fsprojects/Paket#1379]
I'm seeing a lot of this error
Something went wrong while downloading NUnit 3.0.1
Message: Access to the path 'c:\Development\Paket.pms1969\integrationtests\scenarios\i001018-legacy-groups-update\temp\packages\NUnit\lib\portable-net45%2Bwin8%2Bwp8%2Bwpa81%2BXamarin.Mac%2BMonoAndroid10%2BMonoTouch10%2BXamarin.iOS10' is denied.
when running a build of Paket.  In a lot of cases it's fails the build at some stage, sometimes not, but then it fails later (trying to do a .\build.cmd nuget)

Any ideas?

**Comment by forki** [comment]
do you have VS open at that time?

**Comment by pms1969** [comment]
I do but not for Paket (it's a different solution altogether)


here's the tail

Tests run: 68, Errors: 13, Failures: 2, Inconclusive: 0, Time: 576.998201601624 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

Errors and Failures:
1) Test Failure : Paket.IntegrationTests.BasicResolverSpecs.#173 should resolve primary dependency optimistic
     Expected: 2.12.0
Actual: 2.13.0
  Expected: <2.12.0>
  But was:  <2.13.0>


2) Test Error : Paket.IntegrationTests.BasicResolverSpecs.#71 should ignore trailing zero during resolve
   System.Exception : Paket failed with:
        The directory is not empty.

StackTrace:
     at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Paket.NuGetV2.CopyFromCache@388-8.Invoke(Exception _arg3) in c:\Development\Paket\src\Paket.Core\NuGetV2.fs:line 396
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Paket.InstallProcess.CreateModel(String root, Boolean force, DependenciesFile dependenciesFile, LockFile lockFile, FSharpSet`1 packages) in c:\Development\Paket\src\Paket.Core\InstallProcess.fs:line 157
   at Paket.InstallProcess.InstallIntoProjects(InstallerOptions options, DependenciesFile dependenciesFile, LockFile lockFile, FSharpList`1 projects) in c:\Development\Paket\src\Paket.Core\InstallProcess.fs:line 280
   at <StartupCode$Paket-Core>.$PublicAPI.Update@193.Invoke(Unit unitVar0) in c:\Development\Paket\src\Paket.Core\PublicAPI.fs:line 193
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action) in c:\Development\Paket\src\Paket.Core\Utils.fs:line 367
   at Paket.Program.handler@350-16.Invoke(ParseResults`1 results) in c:\Development\Paket\src\Paket\Program.fs:line 350
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args) in c:\Development\Paket\src\Paket\Program.fs:line 55
   at Paket.Program.processCommand@61-1.Invoke(Command command, String[] args) in c:\Development\Paket\src\Paket\Program.fs:line 61
   at Paket.Program.main() in c:\Development\Paket\src\Paket\Program.fs:line 336
   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.TestHelpers.update(String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 46
   at Paket.IntegrationTests.BasicResolverSpecs.#71 should ignore trailing zero during resolve() in c:\Development\Paket\integrationtests\Paket.IntegrationTests\BasicResolverSpecs.fs:line 32

3) Test Error : Paket.IntegrationTests.BindingRedirect.#1248 redirects off
   System.Exception : Paket failed with:
        Access to the path 'c:\Development\Paket\integrationtests\scenarios\i001248-redirects-off\temp\packages\Newtonsoft.Json\lib\portable-net45%2Bwp80%2Bwin8%2Bwpa81%2Bdnxcore50' is denied.
   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.BindingRedirect.#1248 redirects off() in c:\Development\Paket\integrationtests\Paket.IntegrationTests\BindingRedirect.fs:line 279

4) Test Error : Paket.IntegrationTests.BindingRedirect.#1270 redirects from references
   System.Exception : Paket failed with:
        The directory is not empty.

   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.BindingRedirect.#1270 redirects from references() in c:\Development\Paket\integrationtests\Paket.IntegrationTests\BindingRedirect.fs:line 261

5) Test Error : Paket.IntegrationTests.GroupsSpecs.#1018 should resolve Newtonsoft.Json from two groups
   System.Exception : Paket failed with:
        The directory is not empty.

StackTrace:
     at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Paket.NuGetV2.CopyFromCache@388-8.Invoke(Exception _arg3) in c:\Development\Paket\src\Paket.Core\NuGetV2.fs:line 396
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Paket.InstallProcess.CreateModel(String root, Boolean force, DependenciesFile dependenciesFile, LockFile lockFile, FSharpSet`1 packages) in c:\Development\Paket\src\Paket.Core\InstallProcess.fs:line 157
   at Paket.InstallProcess.InstallIntoProjects(InstallerOptions options, DependenciesFile dependenciesFile, LockFile lockFile, FSharpList`1 projects) in c:\Development\Paket\src\Paket.Core\InstallProcess.fs:line 280
   at <StartupCode$Paket-Core>.$PublicAPI.Update@193.Invoke(Unit unitVar0) in c:\Development\Paket\src\Paket.Core\PublicAPI.fs:line 193
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action) in c:\Development\Paket\src\Paket.Core\Utils.fs:line 367
   at Paket.Program.handler@350-16.Invoke(ParseResults`1 results) in c:\Development\Paket\src\Paket\Program.fs:line 350
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args) in c:\Development\Paket\src\Paket\Program.fs:line 55
   at Paket.Program.processCommand@61-1.Invoke(Command command, String[] args) in c:\Development\Paket\src\Paket\Program.fs:line 61
   at Paket.Program.main() in c:\Development\Paket\src\Paket\Program.fs:line 336
   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.TestHelpers.update(String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 46
   at Paket.IntegrationTests.GroupsSpecs.#1018 should resolve Newtonsoft.Json from two groups() in c:\Development\Paket\integrationtests\Paket.IntegrationTests\GroupSpecs.fs:line 13

6) Test Error : Paket.IntegrationTests.InstallSpecs.#1135 should keep lockfile stable when using framework restrictions
   System.Exception : Paket failed with:
        Access to the path 'c:\Development\Paket\integrationtests\scenarios\i001135-stable-install-on-framework-restrictions\temp\packages\Microsoft.Bcl\lib\portable-net40%2Bsl5%2Bwin8%2Bwp8%2Bwpa81' is denied.
   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.TestHelpers.install(String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 50
   at Paket.IntegrationTests.InstallSpecs.#1135 should keep lockfile stable when using framework restrictions() in c:\Development\Paket\integrationtests\Paket.IntegrationTests\InstallSpecs.fs:line 14

7) Test Error : Paket.IntegrationTests.NuGetV3Specs.#1211 update with V3 API should work exactly like V2 API
   System.Exception : Paket failed with:
        Could not download Newtonsoft.Json 8.0.2 from https://api.nuget.org/packages/newtonsoft.json.8.0.2.nupkg.
    The process cannot access the file 'C:\Users\Paul\AppData\Local\NuGet\Cache\Newtonsoft.Json.8.0.2.nupkg' because it is being used by another process.
StackTrace:
     at Paket.NuGetV2.DownloadPackage@658-34.Invoke(String message) in c:\Development\Paket\src\Paket.Core\NuGetV2.fs:line 658
   at Paket.NuGetV2.DownloadPackage@601-33.Invoke(Exception _arg10) in c:\Development\Paket\src\Paket.Core\NuGetV2.fs:line 658
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Paket.InstallProcess.CreateModel(String root, Boolean force, DependenciesFile dependenciesFile, LockFile lockFile, FSharpSet`1 packages) in c:\Development\Paket\src\Paket.Core\InstallProcess.fs:line 157
   at Paket.InstallProcess.InstallIntoProjects(InstallerOptions options, DependenciesFile dependenciesFile, LockFile lockFile, FSharpList`1 projects) in c:\Development\Paket\src\Paket.Core\InstallProcess.fs:line 280
   at <StartupCode$Paket-Core>.$PublicAPI.Update@193.Invoke(Unit unitVar0) in c:\Development\Paket\src\Paket.Core\PublicAPI.fs:line 193
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action) in c:\Development\Paket\src\Paket.Core\Utils.fs:line 367
   at Paket.Program.handler@350-16.Invoke(ParseResults`1 results) in c:\Development\Paket\src\Paket\Program.fs:line 350
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args) in c:\Development\Paket\src\Paket\Program.fs:line 55
   at Paket.Program.processCommand@61-1.Invoke(Command command, String[] args) in c:\Development\Paket\src\Paket\Program.fs:line 61
   at Paket.Program.main() in c:\Development\Paket\src\Paket\Program.fs:line 336
   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.TestHelpers.update(String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 46
   at Paket.IntegrationTests.NuGetV3Specs.#1211 update with V3 API should work exactly like V2 API() in c:\Development\Paket\integrationtests\Paket.IntegrationTests\NuGetV3Specs.fs:line 15

8) Test Failure : Paket.IntegrationTests.PaketCoreSpecs.#1259 install via script
     Expected: 0.33.0
Actual: 1.0.0
  Expected: <0.33.0>
  But was:  <1.0.0>


9) Test Error : Paket.IntegrationTests.UpdateGroupSpecs.#1018 update group legacy
   System.Exception : Paket failed with:
        The directory is not empty.

   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.UpdateGroupSpecs.#1018 update group legacy() in c:\Development\Paket\integrationtests\Paket.IntegrationTests\UpdateGroupsSpecs.fs:line 26

10) Test Error : Paket.IntegrationTests.UpdateGroupSpecs.#1018 update main group
   System.Exception : Paket failed with:
        The directory is not empty.

   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.UpdateGroupSpecs.#1018 update main group() in c:\Development\Paket\integrationtests\Paket.IntegrationTests\UpdateGroupsSpecs.fs:line 15

11) Test Error : Paket.IntegrationTests.UpdatePackageSpecs.#1018 update package in explicit main group
   System.Exception : Paket failed with:
        The directory is not empty.

   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.UpdatePackageSpecs.#1018 update package in explicit main group() in c:\Development\Paket\integrationtests\Paket.IntegrationTests\UpdatePackageSpecs.fs:line 26

12) Test Error : Paket.IntegrationTests.UpdatePackageSpecs.#1018 update package in group
   System.Exception : Paket failed with:
        The directory is not empty.

   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.UpdatePackageSpecs.#1018 update package in group() in c:\Development\Paket\integrationtests\Paket.IntegrationTests\UpdatePackageSpecs.fs:line 37

13) Test Error : Paket.IntegrationTests.UpdatePackageSpecs.#1018 update package in main group
   System.Exception : Paket failed with:
        The directory is not empty.

   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.UpdatePackageSpecs.#1018 update package in main group() in c:\Development\Paket\integrationtests\Paket.IntegrationTests\UpdatePackageSpecs.fs:line 15

14) Test Error : Paket.IntegrationTests.UpdatePackageSpecs.#1178 update specific package
   System.Exception : Paket failed with:
        Access to the path 'c:\Development\Paket\integrationtests\scenarios\i001178-update-with-regex\temp\packages\Microsoft.Bcl\lib\portable-net40%2Bsl5%2Bwin8%2Bwp8%2Bwpa81' is denied.
   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.UpdatePackageSpecs.#1178 update specific package() in c:\Development\Paket\integrationtests\Paket.IntegrationTests\UpdatePackageSpecs.fs:line 48

15) Test Error : Paket.IntegrationTests.UpdatePackageSpecs.#1178 update with Mircosoft.* filter
   System.Exception : Paket failed with:
        Access to the path 'c:\Development\Paket\integrationtests\scenarios\i001178-update-with-regex\temp\packages\Microsoft.Bcl\lib\portable-net40%2Bsl5%2Bwin8%2Bwp8%2Bwpa81' is denied.
   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in c:\Development\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.UpdatePackageSpecs.#1178 update with Mircosoft.* filter() in c:\Development\Paket\integrationtests\Paket.IntegrationTests\UpdatePackageSpecs.fs:line 59


Running build failed.
Error:
Fake.UnitTestCommon+FailedTestsException: NUnit test failed (15).
   at Fake.NUnitSequential.NUnit(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\NUnit\Sequential.fs:line 45
   at FSI_0001.Build.clo@169-12.Invoke(Unit _arg7) in c:\Development\Paket\build.fsx:line 170
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 483

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                  Duration
------                  --------
Clean                   00:00:00.0044705
AssemblyInfo            00:00:00.0446613
Build                   00:00:33.1542759
BuildPowerShell         00:00:08.6236533
RunTests                00:00:14.1929781
CleanDocs               00:00:00.0021291
GenerateHelp            00:00:28.5718239
GenerateReferenceDocs   00:00:21.0013183
GenerateDocs            00:00:00.0001847
All                     00:00:00.0001539
Total:                  00:11:24.9685030
Status:                 Failure
---------------------------------------------------------------------
  1) Fake.UnitTestCommon+FailedTestsException: NUnit test failed (15).
   at Fake.NUnitSequential.NUnit(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\NUnit\Sequential.fs:line 45
   at FSI_0001.Build.clo@169-12.Invoke(Unit _arg7) in c:\Development\Paket\build.fsx:line 170
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 483
---------------------------------------------------------------------

**Comment by forki** [comment]
strange then something else is blocking the paths

**Comment by pms1969** [comment]
ok, never mind.  thought you might have seen it in the past... :-(

I'll keep trying different things until I get it right.  migth even have to "turn it off and on again"

**Comment by pms1969** [comment]
actually, try tho I might, I've not been able to resolve this.

Anyone running windows 10, and tried building from a fresh clone?

**Comment by forki** [comment]
yeah. I'm running on Win 10 - appveyor and travis bukild well as well.

**Comment by pms1969** [comment]
bizarre stuff.  I doesn't always happen to the same tests, but it happens consistently.  Inside VS, I can get the resharper runner up and going and run the same test 10 time in a row (just by itself) and get 4 or 5 failures.

Looking at where it goes wrong (output below) and exactly what it's doing when it goes wrong, I'm noticing it's at the point it's trying to download/extract the file (obviously the message points you there), but what strikes me as significant is that the ExtractPackage method in RestoreProcess.fs and it's subordinate functions are all async.  I'm wondering if it's my machine being under load/caching some file io, that might be causing some issues.  Hard Drive is an SSD, and so should cope with the throughput, but just wondering, and putting it out there in case someone has some ideas.

OUTPUT (successful run):
```
C:\code\Paket\integrationtests\scenarios\i001018-legacy-groups-update\temp already exists.
C:\code\Paket\bin\paket.exe update nuget Newtonsoft.json group Main
```

OUTPUT (failed run):
```
System.Exception : Paket failed with:
	Access to the path 'C:\code\Paket\integrationtests\scenarios\i001018-legacy-groups-update\temp\packages\Newtonsoft.Json\lib\portable-net45%2Bwp80%2Bwin8%2Bwpa81%2Bdnxcore50' is denied.

   at Microsoft.FSharp.Core.Operators.FailWith[T](String message)
   at Paket.IntegrationTests.TestHelpers.directPaket(String command, String scenario) in C:\code\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 42
   at Paket.IntegrationTests.TestHelpers.paket(String command, String scenario) in C:\code\Paket\integrationtests\Paket.IntegrationTests\TestHelper.fs:line 48
   at Paket.IntegrationTests.UpdatePackageSpecs.#1018 update package in explicit main group() in C:\code\Paket\integrationtests\Paket.IntegrationTests\UpdatePackageSpecs.fs:line 26

C:\code\Paket\integrationtests\scenarios\i001018-legacy-groups-update\temp already exists.
C:\code\Paket\bin\paket.exe update nuget Newtonsoft.json group Main
Paket version 2.41.1.0
Updating Newtonsoft.json in C:\code\Paket\integrationtests\scenarios\i001018-legacy-groups-update\temp\paket.dependencies group Main
Resolving packages for group Main:
 - Newtonsoft.Json 8.0.2
 - NUnit 2.6.1
Locked version resolution written to C:\code\Paket\integrationtests\scenarios\i001018-legacy-groups-update\temp\paket.lock
Something went wrong while downloading Newtonsoft.Json 8.0.2
Message: The directory is not empty.

  ==> Trying again
Downloading Newtonsoft.Json 8.0.2
Something went wrong while downloading Newtonsoft.Json 8.0.2
Message: Access to the path 'C:\code\Paket\integrationtests\scenarios\i001018-legacy-groups-update\temp\packages\Newtonsoft.Json\lib\portable-net45%2Bwp80%2Bwin8%2Bwpa81%2Bdnxcore50' is denied.
  ==> Last trial
Downloading Newtonsoft.Json 8.0.2
```

**Comment by matthid** [comment]
Please let us know if this has not been fixed already.
