### ISSUE TITLE
No way to set the source encoding when using Paket Pack

### ISSUE THREAD

**Issue by galaxystar** [fsprojects/Paket#1503]
I'm receiving an error when pushing a nuget package to my Nexus repository. This package is built using ``Paket Pack output ./``. I use the exact same command on other packages, and there are no issues. After some research I've narrowed it down to the error below; ZipException invalid stored block lengths. Which seems to be associated with the source encoding. I see that paket supports preserving nuget's source encoding when converting a nuget package, but I do not see anything for specifying it when packaging. 

It would be nice if we could specify the encoding in the package template and/or on the command line.

Error: 
```
jvm 1    | Caused by: java.util.zip.ZipException: invalid stored block lengths
jvm 1    | 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164) ~[na:1.8.0_45]
jvm 1    | 	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194) ~[na:1.8.0_45]
jvm 1    | 	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140) ~[na:1.8.0_45]
jvm 1    | 	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118) ~[na:1.8.0_45]
jvm 1    | 	at com.sonatype.nexus.plugins.nuget.odata.NuspecSplicer.extractNuspec(NuspecSplicer.java:133) ~[na:na]
````

Reference: http://stackoverflow.com/questions/25235229/extracting-zipped-file-from-resourcestream-throws-error-invalid-stored-block-le

Reproduction steps:
1. Make a package from here: https://github.com/amplitude/unity-plugin/tree/master/Assets
2. And attempt to upload the package to a nexus server ~v2.12. 
Note: Unzipping on the command line seems to understand it fine.

Thanks!

**Comment by galaxystar** [comment]
I've further narrowed this down to NupkgWrite.fs line 197. We use the ZipArchive signature that does not take the entry name encoding parameter: https://msdn.microsoft.com/en-us/library/hh875101(v=vs.110).aspx
Again it would be nice if we can force the package to be encoded in a certain format.

This may be related, definitely interested and specifically mentions Paket: https://github.com/NuGet/Home/issues/1381

**Comment by forki** [comment]
I assume there is a "right" encoding and it doesn't really make sense for the user to specify that. 
But which is the right encoding and can we specify it directly?

**Comment by forki** [comment]
I created an account and it looks like I can reproduce

**Comment by galaxystar** [comment]
I'm not sure, none of the files seem to use any non ANSI characters worth encoding. I only suggest being able to specify the encoding because that's how other package managers seemed to get around this issue. Something that "just works" would be ideal, but I expect that it would also be harder to implement with more edge cases.
