### ISSUE TITLE
Unable to remove dangling dependency 

### ISSUE THREAD

**Issue by theimowski** [fsprojects/Paket#1596]
### Description

Unable to remove dangling dependency - `NuGet.CommandLine` is defined in `paket.dependencies`, but not used by any `paket.references`

### Repro steps

1. checkout https://github.com/theimowski/suave/commit/8dd7d7419edb9aa2ce58721718be6af58b894fc4
2. run `paket.exe -v remove nuget NuGet.CommandLine group Build`

### Expected behavior

`NuGet.CommandLine` should be removed from `paket.dependencies`

### Actual behavior

```
C:\github\suave (merge_nupkgs)
λ tools\paket.exe -v remove nuget NuGet.CommandLine group Build
Paket version 2.58.14.0
found: C:\github\suave\paket.dependencies
Paket failed with:
        The given key was not present in the dictionary.
StackTrace:
     at Microsoft.FSharp.Collections.MapTreeModule.find[TValue,a](IComparer`1 comparer, TValue k, MapTree`2 m)
   at Paket.ProjectFileModule.hasPackageInstalled(GroupName groupName, PackageName package, ProjectFile project)
   at Paket.RemoveProcess.removeFromProjects@73(PackageName packageName, Boolean interactive, GroupName groupName, IEnumerable`1 projects)
   at Paket.RemoveProcess.Remove@79-8.Invoke(ProjectFile[] arg00)
   at Paket.RemoveProcess.remove(FSharpFunc`2 removeFromProjects, String dependenciesFileName, GroupName groupName, PackageName package, Boolean force, Boolean hard, Boolean installAfter)
   at <StartupCode$Paket-Core>.$PublicAPI.Remove@433-9.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Program.handler@342-13.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   at Paket.Program.processCommand@61-1.Invoke(Command command, String[] args)
   at Paket.Program.main()
```
### Known workarounds

One can remove the dependency from `paket.dependencies` manually - however I'm not sure, what command should I invoke afterwards to update `paket.lock`, so that other dependencies are not modified?

**Comment by forki** [comment]
Bug is fixed.

> One can remove the dependency from paket.dependencies manually - however I'm not sure, what command should I invoke afterwards to update paket.lock, so that other dependencies are not modified?

"paket install"

**Comment by theimowski** [comment]
Thanks. With Paket 2.59.0 this is result of running `paket remove nuget NuGet.CommandLine group Build`: https://github.com/theimowski/suave/commit/6cadb6d84eafdbed81aa3368f2d281df47626784  - is this desired behavior that dependencies have been updated?

**Comment by forki** [comment]
yes it's running install and is detecting a change. maybe we should restrict install to the touched group

**Comment by theimowski** [comment]
ok my fault - I've missed the `--no-install` switch. Re restricting install to the group only - probably a minor "nice to have". However there's one thing, which could deserve its own issue: the dependency was the only one in this group - after running the command, group got orphaned [(see here)](https://github.com/theimowski/suave/commit/6cadb6d84eafdbed81aa3368f2d281df47626784#diff-b27553841b4413a24ed1b9aff865105bL13)

**Comment by forki** [comment]
yes please create 2 new issues ;-)
