### ISSUE TITLE
109 tests from Paket.Tests project

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#1597]
Master branch.
```
Test Run Summary
  Overall result: Failed
  Test Count: 724, Passed: 613, Failed: 109, Inconclusive: 0, Skipped: 2
    Failed Tests - Failures: 24, Errors: 85, Invalid: 0
    Skipped Tests - Ignored: 1, Explicit: 0, Other: 1
  Start time: 2016-04-12 09:14:27Z
    End time: 2016-04-12 09:14:36Z
    Duration: 8.978 seconds
```
Line this:
```
107) Error : Paket.ReadPackagesConfigSpecs.can read xunit.visualstudio.packages.config
System.ArgumentException : The input list was empty.
Parameter name: list
   at Microsoft.FSharp.Collections.ListModule.Head[T](FSharpList`1 list)
   at Paket.ReadPackagesConfigSpecs.can read xunit.visualstudio.packages.config() in D:\github\Paket\tests\Paket.Tests\PackagesConfig\ReadConfig.fs:line 11

108) Error : Paket.WritePackagesConfigSpecs.can write asp.net.packages.config
System.IO.DirectoryNotFoundException : Could not find a part of the path 'd:\github\Paket\packages\test\NUnit.ConsoleRunner\tools\PackagesConfig\asp.net.packages.config'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at Paket.WritePackagesConfigSpecs.can write asp.net.packages.config() in D:\github\Paket\tests\Paket.Tests\PackagesConfig\WriteConfig.fs:line 22

106) Error : Paket.ProjectFile.TargetFrameworkSpecs.should detect TargetFramework in Project2 proj file
System.NullReferenceException : Object reference not set to an instance of an object.
   at Paket.ProjectFile.TargetFrameworkSpecs.should detect TargetFramework in Project2 proj file() in D:\github\Paket\tests\Paket.Tests\ProjectFile\TargetFrameworkSpecs.fs:line 10
```

**Comment by forki** [comment]
can you elaborate?!

**Comment by vasily-kirichenko** [comment]
Sorry, everything is ok if I run `build.cmd`. I just tried `nunit3-console.exe ..\..\..\..\tests\Paket.Tests\bin\Release\Paket.Tests.dll` with the results above.
