### ISSUE TITLE
Nuget to Paket conversion fails with uninformative error

### ISSUE THREAD

**Issue by sarudak** [fsprojects/Paket#1654]
When attempting to run .paket/paket.exe convert-from-nuget I get the error message:

Installing to C:\src\blah\blah\blah.csproj
    - Deleting Paket Reference nodes
Paket failed with:
        This operation would create an incorrectly structured document.

Which is completely uninformative as to what is actually wrong. I can only assume that Paket is making some kind of assumption about the structure of the csproj file that is invalid but there seems to be no way to find out what expectations are not being met. Full stack trace from verbose mode follows.

StackTrace:
     at System.Xml.Linq.XDocument.ValidateDocument(XNode previous, XmlNodeType allowBefore, XmlNodeType allowAfter)
   at System.Xml.Linq.XContainer.AddNodeSkipNotify(XNode n)
   at Paket.Xml.Linq.ensurePathExists@89.Invoke(XContainer parent, String node)
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at Paket.BindingRedirects.indentAssemblyBindings(XContainer config)
   at Paket.BindingRedirects.applyBindingRedirects(Boolean isFirstGroup, Boolean cleanBindingRedirects, IEnumerable`1 al
lKnownLibs, IEnumerable`1 bindingRedirects, String configFilePath)
   at Paket.BindingRedirects.applyBindingRedirectsToFolder@177-1.Invoke(String configFilePath)
   at Paket.BindingRedirects.applyBindingRedirectsToFolder@166.Invoke(ProjectFile projectFile)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at Paket.InstallProcess.InstallIntoProjects(InstallerOptions options, Boolean forceTouch, DependenciesFile dependenci
esFile, LockFile lockFile, FSharpList`1 projectsAndReferences)
   at Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions options)

   at <StartupCode$Paket-Core>.$PublicAPI.Install@170.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Program.handler@340-11.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] ar
gs)
   at Paket.Program.processCommand@61-1.Invoke(Command command, String[] args)
   at Paket.Program.main()

**Comment by forki** [comment]
Can you please try to come up with a minimal repro?

**Comment by sarudak** [comment]
I tried putting together a version of the csproj file that could be tested in isolation but it runs through the conversion fine. If I sent you a copy of the csproj file (not the simplified one) would that be enough?

**Comment by forki** [comment]
We can try that. Sforkmann @ gmail

**Comment by sarudak** [comment]
We managed to resolve the issue. Thanks.
