### ISSUE TITLE
Regression: VCProj failed with "Unable to parse ProjectReference"

### ISSUE THREAD

**Issue by tommysu** [fsprojects/Paket#1657]
### Description

Please provide a succinct description of your issue.

We updated to 2.63.2.0  from 2.54.0.0 and our vcproj with references to boost is failing to parse.  
 
Paket failed with:
        unable to parse ProjectReference
StackTrace:
     at Paket.ProjectFileModule.forceGetInnerText@1061-5.Invoke(String message)
   at Paket.ProjectFileModule.getInterProjectDependencies@1063.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.InstallProcess.dependencies@206-11[a](GroupName groupName, FSharpFunc`2 findDependencies, Dictionary`2 projectCache, Dictionary`2 dependencyGraph, Dictionary`2 referenceFiles, ProjectFile projectFile)
   at Paket.InstallProcess.applyBindingRedirects@223-3.Invoke(ProjectFile projectFile)
   at Paket.BindingRedirects.applyBindingRedirectsToFolder@166.Invoke(ProjectFile projectFile)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at Paket.InstallProcess.InstallIntoProjects(InstallerOptions options, Boolean forceTouch, DependenciesFile dependenciesFile, LockFile lockFile, FSharpList`1 projectsAndReferences)
   at Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions options)
   at <StartupCode$Paket-Core>.$PublicAPI.Install@170.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Program.handler@340-11.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   at Paket.Program.processCommand@61-1.Invoke(Command command, String[] args)
   at Paket.Program.main()

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a vcproj with 2.54..0.0 with native project reference to Boost

2. run paket install

3. Build 

4. Upgrade to 2.63.2.0

5. run paket install 

### Expected behavior

paket install to run correctly

### Actual behavior

Error on paket install that "Unable to parse ProjectReference"

### Known workarounds

Go back to the older version

### Related information 

* Operating system
Windows 10
* Branch
* .NET Runtime, CoreCLR or Mono Version
.net 4.6
* Performance information, links to performance testing scripts

**Comment by forki** [comment]
can you send me such a csproj file?

**Comment by acmore** [comment]
Hi it's not necessary c# project. Seems that paket cannot parse the project reference. Here is a sample repo.

[TestPaket.zip](https://github.com/fsprojects/Paket/files/248505/TestPaket.zip)

**Comment by forki** [comment]
I can't reproduce with the zip. What do I need to do exactly?

**Comment by konste** [comment]
Typically "Paker Install" was crashing. We figured undocumented (?) --Verbose option, and it gives us call stack at the time of the crash. What else can we do to get more specific information about the caus of the problem?

**Comment by forki** [comment]
How can I reproduce that with the zip? install works for me

**Comment by konste** [comment]
New repro created (attached). I think the culprit is that referenced project is a static library.
[UnableToParseProjectReference.zip](https://github.com/fsprojects/Paket/files/249285/UnableToParseProjectReference.zip)

**Comment by konste** [comment]
I don't know what Paket is trying to do with the Project reference, but in this case it is used solely to establish project build order and I believe may be safely ignored by paket. Just don't crash on it.

**Comment by forki** [comment]
I can reproduce. thanks
