### ISSUE TITLE
Paket Simplify with Framework set to auto-detect fails with 'the framework restriction could not be determined'

### ISSUE THREAD

**Issue by baronfel** [fsprojects/Paket#1737]
### Description

Using the `framework: auto-detect` ability of paket.dependencies prevents the user from running `paket simplify`. The following error is produced:
```
C:\code\opus\Api.Tenant [master ≡ +2 ~0 -0 !]> .paket/paket simplify --verbose
Paket version 3.1.3.0
found: C:\code\opus\Api.Tenant\paket.dependencies
Parsing C:\code\opus\Api.Tenant\paket.dependencies
Paket failed with:
        The framework restriction could not be determined.
StackTrace:
     at Paket.Requirements.getRestrictionList(FrameworkRestrictions frameworkRestrictions)
   at <StartupCode$Paket-Core>.$DependenciesFile.SimplifyFrameworkRestrictions@604.Invoke(DependenciesFile dependenciesFile, DependenciesGroup group)
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at Paket.Simplifier.simplify@68.Invoke(LockFile _arg1)
   at Chessie.ErrorHandling.Trial.fSuccess@66-11[p,r,q](FSharpFunc`2 f, p x, FSharpList`1 msgs)
   at <StartupCode$Paket-Core>.$PublicAPI.fSuccess@1-2(FSharpFunc`2 f, PaketEnv x, FSharpList`1 msgs)
   at <StartupCode$Paket-Core>.$PublicAPI.Simplify@91.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Program.handler@418-15.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   at Paket.Program.processCommand@61-1.Invoke(Command command, String[] args)
   at Paket.Program.main()
``` 

### Repro steps

Use `framework: auto-detect` in your paket.dependencies, then try to simplify.

### Expected behavior

The framework to use is inferred from the projects in the solution pre-simplify.

### Actual behavior

The exception above is presented.

### Known workarounds

Specify the exact framework in the paket.dependencies file.

### Related information 

* Win10
* Master, paket 3.1.3.0
* .NET Runtime 4.6.1

**Comment by baronfel** [comment]
I was going to take a look at this one after work today.

**Comment by baronfel** [comment]
Ok, got it to work. PR incoming.  This was a little tricky/disruptive, though.

**Comment by AndersJuul** [comment]
I still have issues with the framework: auto-detect -- running paket 3.19.3.0. Same response, 
The framework restriction could not be determined.

But according to this it should be resolved?

**Comment by forki** [comment]
@Anders.Juul sorry just saw this comment. Can you please create an issue with a repro sample? Thx
