### ISSUE TITLE
Error Downloading Licence

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#1741]
### Description

Paket 3 cannot download "Yaaf.AdvancedBuilding == 1.14.0"

```
redirects on
source https://nuget.org/api/v2
nuget Yaaf.AdvancedBuilding == 0.14.0
```

### Expected behavior

Download the package

### Actual behavior

```
$ .paket/paket.exe update
Paket version 3.1.5.0
Resolving packages for group Main:
 - Yaaf.AdvancedBuilding 0.14.0
 - FAKE 4.29.0
 - FSharp.Formatting 2.14.4
 - FSharpVSPowerTools.Core 2.3.0
 - FSharp.Compiler.Service 2.0.0.6
C:\PROJ\Yaaf.FSharp.Scripting\paket.lock is already up-to-date
Something went wrong while downloading Yaaf.AdvancedBuilding 0.14.0
Message: Could not find a part of the path.
  ==> Trying again
Downloading Yaaf.AdvancedBuilding 0.14.0
Something went wrong while downloading Yaaf.AdvancedBuilding 0.14.0
Message: Could not find a part of the path.
  ==> Last trial
Downloading Yaaf.AdvancedBuilding 0.14.0
Paket failed with:
        Could not find a part of the path.



Downloading license for Yaaf.AdvancedBuilding 0.14.0 to C:\Users\dragon\AppData\Local\NuGet\Cache\Yaaf.AdvancedBuilding.0.14.0.license.html
Paket failed with:
        Could not find a part of the path.
StackTrace:
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Paket.NuGetV2.cleanup(DirectoryInfo dir)
   at Paket.NuGetV2.ExtractPackage@428-12.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Microsoft.FSharp.Collections.IEnumerator.map@111.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@713[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at Paket.InstallProcess.InstallIntoProjects[a](InstallerOptions options, Boolean forceTouch, DependenciesFile dependenciesFile, LockFile lockFile, FSharpList`1 projectsAndReferences, FSharpMap`2 updatedGroups)
   at Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions options)
   at <StartupCode$Paket-Core>.$PublicAPI.Update@194.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Program.handler@416-16.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   at Paket.Program.processCommand@61-1.Invoke(Command command, String[] args)
   at Paket.Program.main()

```

### Known workarounds

None

**Comment by forki** [comment]
any ideas what is going wrong?

**Comment by forki** [comment]
Please retry

**Comment by matthid** [comment]
I have no idea whats going on and I still have this with `3.1.9.0`. I might be able to take a look at the weekend.

**Comment by forki** [comment]
Argh. I fixed the one I reproduced. But seems there is more.
On Jun 23, 2016 8:10 PM, "Matthias Dittrich" <notifications@github.com>
wrote:

I have no idea whats going on and I still have this with 3.1.9.0. I might
be able to take a look at the weekend.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/fsprojects/Paket/issues/1741#issuecomment-228134558>,
or mute the thread
<https://github.com/notifications/unsubscribe/AADgNL-080twKFKkSPKIR0bwEbElej5zks5qOsv8gaJpZM4I5LJx>
.

**Comment by matthid** [comment]
![paket_error_1741](https://cloud.githubusercontent.com/assets/1866463/16342469/a390528e-3a32-11e6-842c-9c08625ddbc4.png)

Before fixing: Any idea why we use `Uri.UnescapeDataString`? Should such paths be supported (looks like my package is just invalid, but there might be a paket bug as well)?

**Comment by matthid** [comment]
BTW: The package was build by nuget.exe on linux. Seems like they regressed some path bug. Feels like its time to switch to paket pack :)

**Comment by forki** [comment]
I think replace these paths later in some cleaup function.

**Comment by matthid** [comment]
I'm not sure I understand. Basically the question is how we want to handle files with `\` in their name (which is a valid character on unix).

- Should we just throw here and tell the user that they should package their stuff in way to be compatible across platforms? 
- Throw a better error message on windows?
- Replace `\` with `/` and make it work the same on both platforms?
- Have different behavior on both platforms (= create the file on unix and the folder on Windows)

**Comment by forki** [comment]
Tbh I have no idea. If we can make it reliably work then silently
"patching" the package is fine.
