### ISSUE TITLE
Question: Evaluating MSBuild-Properties from paket pack

### ISSUE THREAD

**Issue by Dirk-Kuypers** [fsprojects/Paket#1949]
We want to split up a huge C# project with around 400 projects into smaller components which should be delivered as nuget packages. I am just looking into Paket because it seems to be very promising, so please be gentle if this question seems dumb.

### Description

In our C# project files we have a global property called $(RootCodeDir) which is set to the root directory of our software if not set from outside:

    <RootCodeDir Condition=" '$(RootCodeDir)' == '' ">$(MSBuildThisFileDirectory.Substring(0, $(MSBuildThisFileDirectory.IndexOf(`repo`))))</RootCodeDir>

With this trick we can ensure that every assembly is written to the same output directory, f.i.:
    <OutputPath>$(RootCodeDir)\repo\bin\debug\</OutputPath>

And if we move around the folder of the project we do not have to change the project file and fiddle with changing the path at multiple locations from ..\..\.. to ..\..

In the example below I have removed the $(RootCodeDir) from the OutputPath, but as pack symbols tries to pack some global files with $(RootCodeDir) in their path, it fails.

c:\repo\path\to\my\project>..\.paket\paket.exe --verbose pack symbols output out buildplatform x86 buildconfig Release_Package
Paket version 3.21.0.0
found: c:\repo\paket.dependencies
Parsing c:\repo\paket.dependencies
Loading assembly metadata for c:\repo\path\to\my\project\bin\x86\Release_Package\my.dll
Paket failed with:
        Could not find a part of the path 'c:\repo\path\to\my\project\$(RootCodeDir)\repo'.
StackTrace:
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at <StartupCode$Paket-Core>.$ProjectFile.GetCompileItems@1626.Invoke(CompileItem compileItem)
   at Microsoft.FSharp.Collections.IEnumerator.map@111.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@713[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Collections.IEnumerator.map@111.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.PackageProcess.convertToSymbols(ProjectFile projectFile, Boolean includeReferencedProjects, TemplateFile templateFile)
   at Paket.PackageProcess.optWithSymbols@185-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Paket.PackageProcess.allTemplates@209-2.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@706[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Collections.IEnumerator.map@111.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@542-1.Invoke(Unit unitVar0)
   at Microsoft.FSharp.Collections.Generator.appG[a](Generator`1 g)
   at Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.PackageProcess.Pack[a](String workingDir, DependenciesFile dependenciesFile, String packageOutputPath, FSharpOption`1 buildConfig, FSharpOption`1 buildPlatform, FSharpOption`1 version, IEn
umerable`1 specificVersions, FSharpOption`1 releaseNotes, FSharpOption`1 templateFile, FSharpOption`1 excludedTemplates, Boolean lockDependencies, Boolean minimumFromLockFile, Boolean pinProjectRefere
nces, Boolean symbols, Boolean includeReferencedProjects, FSharpOption`1 projectUrl)
   at Paket.Program.main@403-20.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
   at Paket.Program.main$cont@380(ParseResults`1 results, Boolean silent, Unit unitVar)
   at Paket.Program.main()

### Expected behavior

Adding and using MSBuild properties in my csproj file should work.;-)

### Known workarounds

Ok. I workaround would be (and I can confirm it works) to add relative paths again instead of the property, but then I am not that free any more regarding the placement of single projects/components in my directory tree.

**Comment by forki** [comment]
Can you please create a small repro of that issue and I will take a look. Thanks

**Comment by Dirk-Kuypers** [comment]
[PaketTest.zip](https://github.com/fsprojects/Paket/files/519483/PaketTest.zip)

Ok, here we go. The project itself does not make a lot of sense but I added the RootCodeDir property and used it to change output paths and to change the path to a global assembly file. In reality f.i. we have a shared assembly file with the version numbers centrally incremented at one place with every build.

If I run the following now, paket fails:
c:\tmp\PaketTest\PaketTestLibrary\PaketTestLibrary>..\.paket\paket.exe pack output out buildplatform AnyCPU
Paket version 3.21.0.0
Paket failed with:
        Could not find a part of the path 'c:\tmp\PaketTest\PaketTestLibrary\PaketTestLibrary\$(MSBuildThisFileDirectory.Substring(0,$(MSBuildThisFileDirectory.IndexOf(`PaketTestLibrary`))))\PaketTest
Library\bin\Release\PaketTestLibrary.dll'.

c:\tmp\PaketTest\PaketTestLibrary\PaketTestLibrary>

The same applies to paket pack symbols.

Thanks for looking into this...

**Comment by jbaehr** [comment]
Microsoft provides a set of APIs for dealing with msbuild files. The most important ones are
 * https://msdn.microsoft.com/en-us/library/microsoft.build.construction.aspx
 * https://msdn.microsoft.com/en-us/library/microsoft.build.evaluation.aspx

While `Microsoft.Build.Construction` works on the xml DOM of the files, `Microsoft.Build.Evaluation` provides everything you need for the evaluation of a project file. This includes property expansion and condition evaluation.
I used both successfully from C# for manipulating msbuild files; maybe you can use them, too, for adressing this issue.
