### ISSUE TITLE
Reference assemblies should not be loaded for execution.

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/Paket#2163]
### Description

When I add Google.Cloud.Logging.Log4Net as a dependency, System.Net.Http gets pulling in as a transitive dependency. This results in paket creating this reference:

``` xml
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v4.6' Or $(TargetFrameworkVersion) == 'v4.6.1' Or $(TargetFrameworkVersion) == 'v4.6.2' Or $(TargetFrameworkVersion) == 'v4.6.3')">
      <ItemGroup>
        <Reference Include="System.Net.Http">
          <HintPath>..\..\packages\System.Net.Http\ref\net46\System.Net.Http.dll</HintPath>
          <Private>True</Private>
          <Paket>True</Paket>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
```
While nuget client creates a reference like so:
``` xml
    <Reference Include="System.Net.Http">
      <Private>True</Private>
    </Reference>
```

This results in this error at runtime:
```
System.BadImageFormatException: Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
File name: 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   at Google.Api.Gax.TaskExtensions.WaitWithUnwrappedExceptions(Task task)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint)
   at Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender.ActivateOptions()
```

That took me several hours to figure out. 👎 

### Known workarounds

Remove System.Net.Http dependency and add it as a framework dependency with copy local as true.

We are on an older Paket version 3.9.6.0. I think I tested with latest too, but will need to confirm a bit later.

**Comment by forki** [comment]
both latest Paket 3 and latest Paket4 beta are not adding `ref` files. can you please check?

**Comment by ctaggart** [comment]
I upgraded to 4.0.0-beta029 and it works great.
