### ISSUE TITLE
Wrong nuget reference hard to find error, improve message 

### ISSUE THREAD

**Issue by asd-and-Rizzo** [fsprojects/Paket#2314]
Add to `paket.dependencies` next line:
```
nuget System.Collections.Immutable: net45
```

Leads to:
```
Paket failed with:
        The given path's format is not supported.
```

Expected:
```
Paket failed with:
        The given path's format is not supported. "nuget System.Collections.Immutable: net45"
```

I have 100 references and some broken, how to find it? Any debug mode for paket?

**Comment by forki** [comment]
paket install -v shows more details

**Comment by asd-and-Rizzo** [comment]
Thanks. I see next. Would it be fruitful to show something in between by default as per my suggestion?
```
  Trying to resolve System.Collections.Immutable:  (from D:\ediscovery-scripts\paket.dependencies)
  - fetching versions for System.Collections.Immutable:
Paket failed with:
        The given path's format is not supported.
StackTrace:
     at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)                           11:15
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at Paket.NuGetV2.getVersionsFailedCacheFileName@806(PackageName packageName, PackageSource source)
   at Paket.NuGetV2.trial@805(FSharpOption`1 alternativeProjectRoot, String root, IEnumerable`1 sources, PackageName packageName, Boolean force)
   at Paket.NuGetV2.GetVersions(Boolean force, FSharpOption`1 alternativeProjectRoot, String root, IEnumerable`1 sources, PackageName packageName)
   at Paket.UpdateProcess.SelectiveUpdate@210.Invoke(ResolverStrategy resolverStrategy, GroupName groupName, PackageName packageName)
   at Paket.UpdateProcess.getSortedAndCachedVersionsF@15(FSharpFunc`2 getSortedVersionsF, Dictionary`2 allVersions, FSharpList`1 sources, ResolverStrategy resolverStrategy, GroupName groupName, PackageName packageName)
   at Paket.UpdateProcess.getVersionsF@126-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.oneStepTo@1372[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i)
   at Microsoft.FSharp.Collections.SeqModule.f@4731-2[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i, Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.result@1388.Invoke(Int32 i)
   at Microsoft.FSharp.Collections.IEnumerator.unfold@239.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.IEnumerator.next@227[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0)
   at Microsoft.FSharp.Collections.IEnumerator.filter@222.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.IsEmpty[T](IEnumerable`1 source)
   at Paket.PackageResolver.getCompatibleVersions$cont@432(ResolverStep currentStep, GroupName groupName, PackageRequirement currentRequirement, FSharpFunc`2 getVersionsF, Boolean globalOverride, FSharpOption`1 globalStrategyForDirectDependencies, FSharpOption`1 globalStrategyForTransitives, Unit unitVar)
   at Paket.PackageResolver.getCompatibleVersions(ResolverStep currentStep, GroupName groupName, PackageRequirement currentRequirement, FSharpFunc`2 getVersionsF, Boolean globalOverride, FSharpOption`1 globalStrategyForDirectDependencies, FSharpOption`1 globalStrategyForTransitives)
   at Paket.PackageResolver.step@652(UpdateMode updateMode, GroupName groupName, FSharpOption`1 globalStrategyForTransitives, FSharpOption`1 globalStrategyForDirectDependencies, FrameworkRestrictions globalFrameworkRestrictions, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, FSharpOption`1 packageFilter, IDictionary`2 rootSettings, Stage stage, StackPack stackpack, IEnumerable`1 compatibleVersions, StepFlags flags)
   at Paket.PackageResolver.Resolve(FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, GroupName groupName, FSharpOption`1 globalStrategyForDirectDependencies, FSharpOption`1 globalStrategyForTransitives, FrameworkRestrictions globalFrameworkRestrictions, FSharpSet`1 rootDependencies, UpdateMode updateMode)
   at <StartupCode$Paket-Core>.$DependenciesFile.resolveGroup@173-1.Invoke(GroupName groupName, b _arg1)
   at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[a,b,c](FSharpFunc`3 f, MapTree`2 m)
   at Microsoft.FSharp.Collections.FSharpMap`2.Map[b](FSharpFunc`2 f)
   at Paket.UpdateProcess.selectiveUpdate(Boolean force, FSharpFunc`2 getSha1, FSharpFunc`2 getSortedVersionsF, FSharpFunc`2 getPackageDetailsF, LockFile lockFile, DependenciesFile dependenciesFile, UpdateMode updateMode, SemVerUpdateMode semVerUpdateMode)
   at Paket.UpdateProcess.SelectiveUpdate(DependenciesFile dependenciesFile, FSharpOption`1 alternativeProjectRoot, UpdateMode updateMode, SemVerUpdateMode semVerUpdateMode, Boolean force)
   at Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions options)
   at <StartupCode$Paket-Core>.$PublicAPI.Install@179.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Program.main@433-10.Invoke(ParseResults`1 results)
   at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
   at Paket.Program.main$cont@420(ParseResults`1 results, Boolean silent, Boolean fromBootstrapper, Unit unitVar)
   at Paket.Program.main()
```

**Comment by forki** [comment]
yeah already working on that
