### ISSUE TITLE
It does not add a binding redirects even though it's needed

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#2351]
`paket install --redirects`

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <gcServer enabled="true" />
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Shouldly" publicKeyToken="6042cbcb05cbc941" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="2.5.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <Paket>True</Paket>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6" />
  </startup>
</configuration>
```

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Expecto.Tests.ExpectoConfigModule.fillFromArgs(ExpectoConfig baseConfig, String[] args)
   at Expecto.Tests.runTestsWithArgs(ExpectoConfig config, String[] args, Test tests)
   at Program.main(String[] args) in ...\Program.fs:line 6
```

**Comment by isaacabraham** [comment]
Does the project have a dependency on FSharp.Core?

**Comment by vasily-kirichenko** [comment]
Yes.

**Comment by vasily-kirichenko** [comment]
>  As in, the test one and / or the "real" one?

What do you mean?

**Comment by matthid** [comment]
After speaking with @forki I'm not sure anymore if this is a bug. Can you please provide a repro?
