### ISSUE TITLE
IOException when paket.reference has File:<package> <folder> link:false

### ISSUE THREAD

**Issue by leandrosalgado** [fsprojects/Paket#2430]
I have in my paket.reference the below reference:

`File:angular-chart.min.js Scripts link:false`

When I run `paket install` or `paket update` I get this error:

> Paket failed with:
> -> IOException: The file '\<My Project Folder\>\Scripts\angular-chart.min.js' already exists.

### Expected behavior

I was expecting that paket would overwrite the destination file or ignore it if no changes were found.

### Actual behavior

Throw an error: 

> Paket failed with:
> -> IOException: The file '\<My Project Folder\>\Scripts\angular-chart.min.js' already exists.

**Comment by forki** [comment]
Can you please create a zip with a repro? Thanks

Am 16.06.2017 17:04 schrieb "leandrosalgado" <notifications@github.com>:

**Comment by matthid** [comment]
Or at least run with the environment variable `PAKET_DETAILED_ERRORS` set to `true` or the verbose option. To get a more usefull error message.

**Comment by leandrosalgado** [comment]
I believe I found the fault code at [Paket.Core/InstallProcess](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/Installation/InstallProcess.fs#L480):

`File.Copy(remoteFilePath,targetFile.FullName)`

My suggestion:
```fsharp
// Set the overwrite flag true
File.Copy(remoteFilePath,targetFile.FullName, true)
```

@forki I reckon with the full error log it isn't necessary anymore to create a repro, thank you.
@matthid Thank you lots for the tip to run paket verbose! 👍 

#### Stacktrace:
```powershell
FileName: angular-chart.min.js
Performance:
 - Disk IO: 1 second
 - Runtime: 20 seconds
Paket failed with:
-> IOException: The file '<Project Folder>\Scripts\angular-chart.min.js' already exists.
   StackTrace:
        at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
        at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
        at Paket.InstallProcess.gitRemoteItems@453.Invoke(Tuple`2 tupledArg)
        at Microsoft.FSharp.Collections.IEnumerator.map@114.DoMoveNext(b& )
        at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
        at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
        at Paket.InstallProcess.InstallIntoProjects[a](InstallerOptions options, Boolean forceTouch, DependenciesFile de
pendenciesFile, LockFile lockFile, FSharpList`1 projectsAndReferences, FSharpMap`2 updatedGroups)
        at Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions opt
ions)
        at <StartupCode$Paket-Core>.$PublicAPI.Install@182.Invoke(Unit unitVar0)
        at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
        at Paket.Program.main@461-10.Invoke(ParseResults`1 results)
        at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseRe
sults`1 result)
        at Paket.Program.processCommand[a](Boolean silent, FSharpFunc`2 commandF, ParseResults`1 result)
        at Paket.Program.main$cont@448(ParseResults`1 results, Boolean silent, Boolean fromBootstrapper, Unit unitVar)
        at Paket.Program.main()
```

**Comment by forki** [comment]
cool. Awaiting pull request ;-)

**Comment by matthid** [comment]
Hm I'm not sure if we should just overwrite user files... What if the user has changes them manually after install?
I know people should have stuff in source control but I think we need a more explicit way. Mayba a warning with a hint what to do to make paket overwrite?

**Comment by leandrosalgado** [comment]
I reckon it's fine because as the user is referencing a third-party library and it's expected that paket will keep this library synchronized with the library source(e.g. GitHub and son on).

My opinion, if the user would decide to make changes in this file it should be done without reference this file through paket.

PS.: If I misunderstood any concept of paket please let me know.

**Comment by matthid** [comment]
@leandrosalgado well, I somehow was thinking about content files. But still, if you explicitely set `link:false` people might assume it is now in their control. Maybe we can try to find the original author and cc him.

**Comment by matthid** [comment]
Ok github blame feature is awesome :P 
The original issue seems to be https://github.com/fsprojects/Paket/issues/823 it was implemented by @forki .

But that doesn't yield any info about whether paket or the user is in control of that file. As paket copies it into the project directory I'd say the user but as it was apparently introduced as a workaround I'm fine with overwriting as well...

**Comment by forki** [comment]
Yes please send a pull request

Am 17.06.2017 12:26 nachm. schrieb "Matthias Dittrich" <
notifications@github.com>:

**Comment by leandrosalgado** [comment]
Pull request has been sent.

Thank you all! Have a great weekend!
