### ISSUE TITLE
packing on windows with duplicate fsproj file causes lock conflict with self

### ISSUE THREAD

**Issue by daz10000** [fsprojects/Paket#2461]
### Description

A routine projectscaffold build that previously worked has stopped working with a lock conflict on the nupkg file under windows inside GitBash.  The ultimate cause is a stray .fsproj~ file left behind by vim but paket picks up the .fsproj~ file and creates a lock conflict with itself.

### Repro steps

1.  Copy project file  GslCore.fsproj to GslCore.fsproj~  in a ProjectScaffold src/GslCore project folder under windows

Attempt to package a file thus

```
$ .paket/paket.exe pack output "bin" version 0.4.22 releaseNotes  "message"
Paket version 5.1.8
Packed: C:\seq\GslCore\src\GslCore\paket.template
Performance:
 - Runtime: 1 second
Paket failed with:
-> IOException: The process cannot access the file 'C:\seq\GslCore\bin\GslCore.0.4.22.nupkg' because it is being used by another process.
```

With verbose output
```
$ .paket/paket.exe pack --verbose output "bin" version 0.4.22 releaseNotes  "Support for seamless primer generation for non linkered designs"
Paket version 5.1.8
found: C:\seq\GslCore\paket.dependencies
Parsing C:\seq\GslCore\paket.dependencies
Could not find AppDataFolder, try to set the APPDATA environment variable. Using 'C:\seq\GslCore\.paket' instead.
Could not detect a root for our (user specific) temporary files. Try to set the 'HOME' or 'LocalAppData' environment variable!. Using 'C:\seq\GslCore\.paket' instead.
Could not find LocalApplicationData folder, try to set the 'LocalAppData' environment variable. Using 'C:\seq\GslCore\.paket' instead
Loading assembly metadata for C:\seq\GslCore\src\GslCore\bin\Release\GslCore.dll
Loading assembly metadata for C:\seq\GslCore\src\GslCore\bin\Release\GslCore.dll
Packed: C:\seq\GslCore\src\GslCore\paket.template
Performance:
 - Runtime: 1 second
Paket failed with:
-> IOException: The process cannot access the file 'C:\seq\GslCore\bin\GslCore.0.4.22.nupkg' because it is being used by another process.
   StackTrace:
        at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
        at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
        at System.IO.FileStream..ctor(String path, FileMode mode)
        at Paket.NupkgWriter.Write(CompleteCoreInfo core, OptionalPackagingInfo optional, String workingDir, String outputDir)
        at Paket.PackageProcess.Pack@246-4.Invoke(Unit unitVar)
        at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
        at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
        at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
        at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
        at Paket.PackageProcess.Pack[a](String workingDir, DependenciesFile dependenciesFile, String packageOutputPath, FSharpOption`1 buildConfig, FSharpOption`1 buildPlatform, FSharpOption`1 version, IEnumerable`1 specificVersions, FSharpOption`1 releaseNotes, FSharpOption`1 templateFile, FSharpOption`1 excludedTemplates, Boolean lockDependencies, Boolean minimumFromLockFile, Boolean pinProjectReferences, Boolean symbols, Boolean includeReferencedProjects, FSharpOption`1 projectUrl)
        at Paket.Program.main@478-22.Invoke(ParseResults`1 results)
        at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
        at Paket.Program.main$cont@453(ParseResults`1 results, Boolean silent, Boolean fromBootstrapper, Unit unitVar)
        at Paket.Program.main()
```

### Expected behavior
Should ignore the .fsproj~ stray backup left around by vim

### Actual behavior
Encounters a file locked error.

### Known workarounds
Delete the stray backup file.

### Example minimal project file that exercises the bug under windows10,  VS2017 envrionment.
[GslCoreBug.zip](https://github.com/fsprojects/Paket/files/1098366/GslCoreBug.zip)

**Comment by jbaehr** [comment]
This issue still exists and is very annoying... till now I found two reasons for this to happen:
- The project file is duplicated. In my case it was a left-over from a canceled build (e.g. `myproject__iiu5anbn_wpftmp.csproj` just beside `myproject.csproj`)
- completely different template files having accidentally  the same id

While the later case may be more difficult to address, the first one should be easy: Just "uniquify" the list of template files before processing. I currently see something like this from `paket pack` output (using v5.219.0)
```
...
Packaging: C:\...\ProjA\paket.template
Packaging: C:\...\ProjB\paket.template
Wrote: C:\...\ProjA.1.2.3.nupkg
Packaging: C:\...\ProjC\paket.template
Wrote: C:\...\ProjB.1.2.3.nupkg
Packaging: C:\...\ProjC\paket.template
Performance:
 - Runtime: 4 seconds
Paket failed with
-> IOException: The process cannot access the file 'C:\...\ProjC.1.2.3.nupkg' because it is being used by another process.
   StackTrace:
        at System.IO.FileSystem.DeleteFile(String fullPath)
        at System.IO.File.Delete(String path)
        at Paket.NupkgWriter.Write(CompleteCoreInfo core, OptionalPackagingInfo optional, String workingDir, String outputDir) in C:\code\Paket\src\Paket.Core\Packaging\NupkgWriter.fs:line 247
        at Paket.PackageProcess.Pack@244-3.Invoke(Unit unitVar) in C:\code\Paket\src\Paket.Core\Packaging\PackageProcess.fs:line 247
        at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
     --- End of stack trace from previous location where exception was thrown ---
        at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
        at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
        at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
        at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
        at Paket.PackageProcess.Pack[a](String workingDir, DependenciesFile dependenciesFile, String packageOutputPath, FSharpOption`1 buildConfig, FSharpOption`1 buildPlatform, FSharpOption`1 version, IEnumerable`1 specificVersions, FSharpOption`1 releaseNotes, FSharpOption`1 templateFile, FSharpOption`1 excludedTemplates, Boolean lockDependencies, Boolean minimumFromLockFile, Boolean pinProjectReferences, FSharpOption`1 interprojectReferencesConstraint, Boolean symbols, Boolean includeReferencedProjects, FSharpOption`1 projectUrl) in C:\code\Paket\src\Paket.Core\Packaging\PackageProcess.fs:line 241
        at Paket.Dependencies.Pack[b](String outputPath, FSharpOption`1 buildConfig, FSharpOption`1 buildPlatform, FSharpOption`1 version, FSharpOption`1 specificVersions, FSharpOption`1 releaseNotes, FSharpOption`1 templateFile, FSharpOption`1 workingDir, FSharpOption`1 excludedTemplates, FSharpOption`1 lockDependencies, FSharpOption`1 minimumFromLockFile, FSharpOption`1 pinProjectReferences, FSharpOption`1 interprojectReferencesConstraint, FSharpOption`1 symbols, FSharpOption`1 includeReferencedProjects, FSharpOption`1 projectUrl) in C:\code\Paket\src\Paket.Core\PublicAPI.fs:line 748
        at Paket.Program.handleCommand@851-23.Invoke(ParseResults`1 results) in C:\code\Paket\src\Paket\Program.fs:line 851
        at Paket.Program.processWithValidationEx$cont@42[a](Boolean silent, FSharpFunc`2 commandF, a result, Unit unitVar) in C:\code\Paket\src\Paket\Program.fs:line 43
        at Paket.Program.processWithValidationEx[a](FSharpFunc`2 printUsage, Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, a result) in C:\code\Paket\src\Paket\Program.fs:line 35
        at Paket.Program.handleCommand(Boolean silent, Command command) in C:\code\Paket\src\Paket\Program.fs:line 851
        at Paket.Program.main() in C:\code\Paket\src\Paket\Program.fs:line 932
```
Notice the two `Packaging: C:\...\ProjC\paket.template`.

**Comment by daz10000** [comment]
My original case was caused by vim leaving a backup with an .fsproj~ file extension so it wasn’t even a real project file :(

Von meinem iPhone gesendet
