### ISSUE TITLE
CryptographicException: Key not valid for use in specified state.

### ISSUE THREAD

**Issue by lucalandi** [fsprojects/Paket#2627]
### Description

I'm getting this exception from one of our Windows Server 2016 slaves.
This is reproducible with paket versions: 3.27.0, 5.85.8
stderr: Paket failed with
-> CryptographicException: Key not valid for use in specified state.
   
   StackTrace:
        at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
        at Paket.ConfigFile.Decrypt(String salt, String encrypted)
        at Paket.ConfigFile.getAuthFromNode(XmlNode node)
        at Paket.ConfigFile.AddCredentials@173.Invoke(XmlNode _arg1)
        at Chessie.ErrorHandling.Trial.fSuccess@66-11[p,r,q](FSharpFunc`2 f, p x, FSharpList`1 msgs)
        at <StartupCode$Paket-Core>.$PublicAPI.AddCredentials@167-2.Invoke(Unit unitVar0)
        at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
        at Paket.Program.main@729-4.Invoke(ParseResults`1 results)
        at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
        at Paket.Program.main$cont@721(ParseResults`1 results, Boolean silent, Boolean fromBootstrapper, Unit unitVar)
        at Paket.Program.main()

### Repro steps
`cmd: paket config add-credentials https://myget.org/F/feed/api/v2 --username user --password password --verbose`

### Expected behavior

It should not fail.

### Actual behavior

Exceptions thrown.

### Known workarounds
This issue is caused by a local paket.config file which contains an encrypted password that is probably expired if you are getting that exception. The only solution I found is to remove the file in:
`C:\Users\user\AppData\Roaming\Paket\paket.config`
and rerun the command:
`cmd: paket config add-credentials https://myget.org/F/feed/api/v2 --username user --password password --verbose`

**Comment by lucalandi** [comment]
this is happening also on paket version 3.36.1

**Comment by lucalandi** [comment]
This issue is caused by a local paket.config file which contains an encrypted password that is probably expired if you are getting that exception. The only solution I found is to remove the file in:
`C:\Users\user\AppData\Roaming\Paket\paket.config`
and rerun the command:
`cmd: paket config add-credentials https://myget.org/F/feed/api/v2 --username user --password password --verbose`

**Comment by matthid** [comment]
We could probably improve the error message. Thanks for investigating.

**Comment by aminya** [comment]
Install this it works:
https://support.microsoft.com/en-us/help/3000988/-the-profile-for-the-user-is-a-temporary-profile-error-when-you-instal

**Comment by brian6932** [comment]
I'm getting this as well, system info:
```pwsh
❯ $_=Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion';$_.CurrentBuild+'.'+$_.UBR
19044.3448
❯ choco --version
2.2.2
❯ pwsh --version
PowerShell 7.4.0-preview.6
```
