### ISSUE TITLE
paket restore prints TaskCancelledException

### ISSUE THREAD

**Issue by 0x53A** [fsprojects/Paket#2636]
see https://ci.appveyor.com/project/0x53A/paket/build/0.0.1.2#L190

paket restore prints

```
Source 'https://www.nuget.org/api/v2' exception: System.Exception: error ---> System.Exception: Could not retrieve data from 'https://www.nuget.org/api/v2/Packages(Id='libuv',Version='1.10')' ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FSharp.Polyfill.AsyncExtensions.continuation@43[T](FSharpFunc`2 cont, FSharpFunc`2 econt, Task`1 completedTask)
   --- End of inner exception stack trace ---
   at Paket.Utils.getFromUrl@657-8.Invoke(Exception _arg4)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
   --- End of inner exception stack trace ---
   at Paket.NuGetV2.getDetailsFromNuGetViaODataFast@367-1.Invoke(FSharpChoice`2 _arg5)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)
Something failed in GetPackageDetails, trying again with force: Couldn't get package details for package Libuv 1.10 on https://www.nuget.org/api/v2.
```

No way to reproduce (except maybe by repeatedly triggering a build), this is the first time I've seen it

**Comment by enricosada** [comment]
Closing, in the build ci paket print also that information based on an env var.
End user using paket doesnt see it.
