### ISSUE TITLE
[RuntimeGraph] Issues while parsing

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#2667]
### Description

Seems like the sdk20 release added new syntax to the runtime graph files. I saw the following in FAKE:

```
Error:
System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JArray'.
   at Paket.RuntimeGraphParser.readCompatiblityProfilesJ@64-3.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.RuntimeGraphParser.readCompatiblityProfilesJ@61-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.RuntimeGraphParser.readCompatiblityProfilesJ@57.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.RuntimeGraphParser.readRuntimeGraphJ(JObject json)
   at Paket.RuntimeGraphModule.getRuntimeGraphFromNugetCache@211.Invoke(String s)
   ...
```

**Comment by matthid** [comment]
Fixed in https://github.com/fsprojects/Paket/issues/2670
