### ISSUE TITLE
Exception - Could not detect any platforms from 'uap10.1'

### ISSUE THREAD

**Issue by oto313** [fsprojects/Paket#2758]
### Description

I cannot install Nuget package to project, which was successfuly converted from Nuget to Paket.

### Repro steps

1. Convert ASP.NET Core and .NET Core application via command .paket/paket.exe convert-from-nuget. Succesfuly done

2. Add to paket.dependecies another dependency (I added entityframework). It shows "Error during parsing of 'paket.lock'."

see attachment paket.txt ( = paket.lock)

3. When I installed entityframework via Visual Studio extension "Paket for Visual Studio"  it shows exception

### Expected behavior

It should install nuget package without error.

### Actual behavior

Visual studio show error message `"Error during parsing of 'paket.lock'."`

Paket for Visual Studio shows following exception:
```

Adding EntityFramework to path
[paket.txt](https://github.com/fsprojects/Paket/files/1296587/paket.txt)
\paket.dependencies into group Main
Could not detect any platforms from 'uap10.1'
System.Exception: Error during parsing of 'C:\projects\Ris\src\Ris\paket.lock'. ---> System.Exception: invalid parameter 'uap10.1' after >= or < in '< uap10.1)) (&& (>= netstandard1.6) (< netstandard2.0) (< monotouch) (< xamarintvos) (< xamarinwatchos) (< xamarinios) (< xamarinmac)) (&& (< netstandard1.6) (>= netcoreapp1.1)) (>= netcoreapp1.0) (&& (>= netcoreapp1.1) (< netcoreapp2.0))'
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at Paket.Requirements.parseOperand@595(String text, FSharpList`1 cur, String next)
   at Paket.Requirements.parseOperator@571(String text)
   at Paket.Requirements.parseOperand@595(String text, FSharpList`1 cur, String next)
   at Paket.Requirements.parseOperator@571(String text)
   at Paket.Requirements.parseRestrictions(Boolean failImmediatly, String text)
   at Paket.Requirements.InstallSettings.Parse(String text)
   at Paket.LockFileParser.parsePackage@381-1(String s)
   at Paket.LockFileParser.Parse$cont@439-1(FSharpFunc`2 removeBrackets, FSharpList`1 otherGroups, ParseState currentGroup, String details, Unit unitVar)
   at Paket.LockFileParser.Parse$cont@414(FSharpFunc`2 removeBrackets, String line, FSharpList`1 otherGroups, ParseState currentGroup, Unit unitVar)
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at Paket.LockFile.Parse(String lockFileName, String[] lines)
   --- End of inner exception stack trace ---
   at Paket.LockFile.Parse(String lockFileName, String[] lines)
   at Paket.UpdateProcess.SelectiveUpdate(DependenciesFile dependenciesFile, FSharpOption`1 alternativeProjectRoot, UpdateMode updateMode, SemVerUpdateMode semVerUpdateMode, Boolean force)
   at Paket.AddProcess.add(Boolean installToProjects, FSharpFunc`2 addToProjectsF, String dependenciesFileName, GroupName groupName, PackageName package, String version, InstallerOptions options, Boolean installAfter)
   at <StartupCode$Paket-Core>.$PublicAPI.Add@151-17.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Dependencies.Add(FSharpOption`1 groupName, String package, String version, Boolean force, Boolean withBindingRedirects, Boolean cleanBindingRedirects, Boolean createNewBindingFiles, Boolean interactive, Boolean installAfter, SemVerUpdateMode semVerUpdateMode, Boolean touchAffectedRefs)
   at Paket.VisualStudio.Commands.AddPackageProcess.<>c__DisplayClass0_1.<ShowAddPackageDialog>b__3(NugetResult result)
   at Paket.VisualStudio.Commands.PackageGui.AddPackageViewModel.<>c__DisplayClass26_0.<.ctor>b__9()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

### Known workarounds

None

**Comment by matthid** [comment]
Probably outdated `Paket.VisualStudio`...

**Comment by oto313** [comment]
yeah, sorry it should be issue to paket for visual studio, please close

**Comment by enricosada** [comment]
> please close
