### ISSUE TITLE
Paket.Core 5.101 -> 5.119.7 breaks FAKE on linux

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#2861]
### Description

```
-> Folder /home/travis/.nuget/packages/fsharp.compiler.tools/4.1.27 doesn't exist. Did you restore groups NetcoreBuild?
StackTrace:
at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
at <StartupCode$Paket-Core>.$DependencyCache.exprs@200-2.Invoke(Unit unitVar)
at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
at Paket.DependencyCache.SetupGroup(GroupName groupName)
at Fake.Runtime.FakeRuntime.restoreOrUpdate@138(Boolean printDetails, String cacheDir, Dependencies paketDependencies, String groupStr, GroupName groupName, FrameworkIdentifier framework, FileInfo lockFilePath, Unit unitVar0) in /home/travis/build/fsharp/FAKE/src/app/Fake.Runtime/FakeRuntime.fs:line 332
at Fake.Runtime.FakeRuntime.paketCachingProvider(Boolean printDetails, String cacheDir, Dependencies paketDependencies, FSharpOption`1 group) in /home/travis/build/fsharp/FAKE/src/app/Fake.Runtime/FakeRuntime.fs:line 349
at Fake.Runtime.FakeRuntime.prepareAndRunScriptRedirect(Boolean printDetails, FSharpList`1 fsiOptions, String scriptPath, IEnumerable`1 envVars, FSharpFunc`2 onErrMsg, FSharpFunc`2 onOutMsg, Boolean useCache)
at Fake.Runtime.FakeRuntime.prepareAndRunScript(Boolean printDetails, FSharpList`1 fsiOptions, String scriptPath, IEnumerable`1 envVars, Boolean useCache)
at Program.handleCli@80.Invoke(ParseResults`1 runArgs) in /home/travis/build/fsharp/FAKE/src/app/Fake.netcore/Program.fs:line 153
```

So `SetupGroup` is not finding the previously restored packages, see https://travis-ci.org/fsharp/FAKE/builds/291147359

**Comment by matthid** [comment]
I think the reason was that old FAKE runtime was still restoring with old (not lower cased) version. And bootstrapping later failed because it tried to find the lower cased version.
