### ISSUE TITLE
paket install crashes

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/Paket#2895]
```
.paket\paket install
Paket version 5.122.0
Skipping resolver for group Main since it is already up-to-date
...\paket.lock is already up-to-date
Installing into projects:
 - Creating model and downloading packages.

Unhandled Exception:
Unhandled Exception: System.TypeInitializationException: The type initializer for '<StartupCode$Paket-Core>.$InstallModel' threw an exception. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at <StartupCode$Paket-Core>.$InstallModel..cctor()
   --- End of inner exception stack trace ---
   at Paket.RestoreProcess.CreateInstallModel@196-1.Invoke(Tuple`2 _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)
   at <StartupCode$FSharp-Core>.$Control.loop@425-51(Trampoline this, FSharpFunc`2 action)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Control.-ctor@509-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.TypeInitializationException: The type initializer for '<StartupCode$Paket-Core>.$InstallModel' threw an exception. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at <StartupCode$Paket-Core>.$InstallModel..cctor()
   --- End of inner exception stack trace ---
   at Paket.RestoreProcess.CreateInstallModel@196-1.Invoke(Tuple`2 _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)
   at <StartupCode$FSharp-Core>.$Control.loop@425-51(Trampoline this, FSharpFunc`2 action)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Control.-ctor@509-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by matthid** [comment]
Compiler bug or bug in `FSharp.Core`? I don't feel like we have any code which should produce something like this.

**Comment by vasily-kirichenko** [comment]
My CLR seems broken after installing - removing .NET Framework SDK 4.7.1. Reinstalling windows now. Stay tuned :)

**Comment by enricosada** [comment]
@vasily-kirichenko ping, can be closed? was an issue with your local environment?
