### ISSUE TITLE
Assembly resolution problem: MissingMethodException: Microsoft.Extensions.Configuration.ConfigurationBuilder.get_Properties

### ISSUE THREAD

**Issue by aggieben** [fsprojects/Paket#3015]
### Description

In an F♯ console app targeting `netcoreapp2.0`, I'm referencing `Prometheus.Client.MetricServer` 1.1.3.  That package pulls in a pretty big chunk of Microsoft.AspNet.*.  I'm using Paket 5.130.3 to manage dependencies.  At runtime, the console program fails with an exception like this:

```
Unhandled Exception: System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.Object> Microsoft.Extensions.Configuration.ConfigurationBuilder.get_Properties()'.
   at Prometheus.Client.MetricServer.MetricServer.Start()
   at Program.main(String[] argv) in C:\Users\ben\proj\bt\scratch\promclient-paket\Program.fs:line 9
```

The reason this is unexpected (and wrong) is because the supposedly missing method is not missing in any implementation of the assembly (`ConfigurationBuilder.get_Properties` is implemented in all versions of the assembly for all targets).

The problem can be reproduced with C♯ and F♯ if Paket is being used.  If NuGet is used, the problem cannot be reproduced.

### Repro steps

Please provide the steps required to reproduce the problem

1. `dotnet new console -lang F#`

2. `dotnet add package Prometheus.Client.MetricServer`

2. Edit `Program.fs` to look like this:
```
open System

[<EntryPoint>]
let main argv =
    let server = Prometheus.Client.MetricServer.MetricServer(9090)
    server.Start()
    printfn "Hello World from F#!"
    0 // return an integer exit code
```

3. `paket convert-from-nuget`

4. `paket install`

5. `dotnet run`

6.  Observe described failure

Please see https://github.com/aggieben/paket-3015-missingmethodexception 

Just to be extra clear: this can be done with C♯, so one can slightly alter these steps and reproduce it that way as well.

### Expected behavior

Expect no exception to be thrown.

### Actual behavior

See Description.

### Known workarounds

It appears that setting `strategy: min` in `paket.dependencies` will avoid the issue.

**Comment by aggieben** [comment]
It looks like this was a package specific issue and not a Paket problem.  I'm going to close this.  See PrometheusClientNet/Prometheus.Client.MetricServer#3
