### ISSUE TITLE
convert-from-nuget fails with ArgumentException: The option value was None Parameter name: option

### ISSUE THREAD

**Issue by pshrosbree** [fsprojects/Paket#3089]
### Description

Converting a solution with a single F# netcoreapp2.0 project fails with:

```
λ  .\.paket\paket.exe convert-from-nuget
Paket version 5.145.6
Performance:
 - Runtime: 555 milliseconds
Paket failed with
-> ArgumentException: The option value was None
   Parameter name: option
```

### Repro steps

Please provide the steps required to reproduce the problem

1. Create solution with a single F# netcoreapp2.0 project.
2. Create a `.paket` folder in the solution folder
3. Run  .`paket\paket.exe convert-from-nuget`

[A git repository with a repro sample](https://github.com/pshrosbree/paket-fail)

### Expected behavior

After executing `paket.exe convert-from-nuget` I expect the project to be converted to paket

### Actual behavior

paket fails with an argument exception

### Known workarounds

Convert to paket manually

**Comment by matthid** [comment]
can you post the output with verbose flag please? `paket -v convert-from-nuget`

**Comment by pshrosbree** [comment]
```
Paket version 5.145.6
Performance:
 - Runtime: 648 milliseconds
Paket failed with
-> ArgumentException: The option value was None
   Parameter name: option
   StackTrace:
        at Microsoft.FSharp.Core.OptionModule.GetValue[T](FSharpOption`1 option)
        at Paket.ProjectFileModule.dotNetCorePackages@1624.Invoke(XmlNode node)
        at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x)
        at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
        at Paket.NuGetConvert.allVersionsGroupped@254-1.Invoke(Tuple`2 tupledArg)
        at Paket.NuGetConvert.createDependenciesFileR(DirectoryInfo rootDirectory, NugetEnv nugetEnv, CredsMigrationMode mode)
        at Paket.NuGetConvert.createPaketEnv(DirectoryInfo rootDirectory, NugetEnv nugetEnv, CredsMigrationMode credsMirationMode)
        at Paket.NuGetConvert.createResult(DirectoryInfo rootDirectory, NugetEnv nugetEnv, CredsMigrationMode credsMirationMode)
        at Chessie.ErrorHandling.Trial.fSuccess@66-11[p,r,q](FSharpFunc`2 f, p x, FSharpList`1 msgs)
        at Chessie.ErrorHandling.Trial.fSuccess@66-11[p,r,q](FSharpFunc`2 f, p x, FSharpList`1 msgs)
        at Chessie.ErrorHandling.Trial.fSuccess@66-11[p,r,q](FSharpFunc`2 f, p x, FSharpList`1 msgs)
        at <StartupCode$Paket-Core>.$PublicAPI.ConvertFromNuget@124.Invoke(Unit unitVar0)
        at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
        at Paket.Program.handleCommand@753-4.Invoke(ParseResults`1 results)
        at Paket.Program.processWithValidationEx$cont@33[a](Boolean silent, FSharpFunc`2 commandF, a result, Unit unitVar)
        at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
        at Paket.Program.handleCommand(Boolean silent, Command command)
        at Paket.Program.main()
```

**Comment by matthid** [comment]
```
<ItemGroup>
    <PackageReference Include="Argu" Version="5.0.1" />
    <PackageReference Update="FSharp.Core" Version="4.3.4" />
</ItemGroup>
```

I can send a fix to not crash anymore but
@enricosada @forki What does `Update` mean? Do we need to use Update as well when emitting `FSharp.Core` in our msbuild integration?

**Comment by forki** [comment]
IIRC it means to override the one that ships with sdk.

Am 27.02.2018 18:58 schrieb "Matthias Dittrich" <notifications@github.com>:
