### ISSUE TITLE
Exception during restore

### ISSUE THREAD

**Issue by lexarchik** [fsprojects/Paket#3290]
### Description

On one particular machine (win10x64) restore and install fails with
`NotSupportedException: The given path's format is not supported.`
Full log:
```text
.\.paket\paket.exe : Paket failed with
At line:1 char:1
+ .\.paket\paket.exe install -v 2> install.log
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Paket failed with:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
-> NotSupportedException: The given path's format is not supported.

   StackTrace:

        at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
        at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
        at Paket.ProcessHelper.files@17-1.Invoke(String path)
        at Micro
soft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
        at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
        at Microsoft.FSharp.Collections.Internal.IEnumerator.next@187[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 
started, Unit unitVar0)
        at Microsoft.FSharp.Collections.Internal.IEnumerator.filter@182.System-Collections-IEnumerator-MoveNext()
        at Microsoft.FSharp.Collections.SeqModule.oneStepTo@984[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 
enumeratorR, Int32 i)
        at Microsoft.FSharp.Collections.SeqModule.action@4236-1[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 
enumeratorR, Int32 i, Unit unitVar0)
        at Microsoft.FSharp.Collections.SeqModule.result@1000.Invoke(Int32 i)
        at Microsoft.FSharp.Collections.Internal.IEnumerator.unfold@199.DoMoveNext(b& curr)
        at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
        at Microsoft.FSharp.Collections.SeqModule.IsEmpty[T](IEnumerable`1 source)
        at Paket.ProcessHelper.tryFindFile(IEnumerable`1 dirs, String file)
        at Paket.NuGetCache.TryGetFallbackFolder()
        at Paket.NuGetCache.TryGetFallbackNupkg(PackageName packageName, SemVerInfo version)
        at Paket.NuGet.getFromFallbackFolder@812(SemVerInfo version, PackageName packageName, String targetFileName, 
Unit unitVar0)
        at Paket.NuGet.download@824-3.Invoke(Unit unitVar)
        at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
        at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, 
FSharpAsync`1 computation)
        at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 
computation, FSharpOption`1 timeout)
        at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, 
FSharpOption`1 cancellationToken)
        at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
        at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
        at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit 
unitVar0)
        at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit 
unitVar0)
        at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
        at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
        at Paket.InstallProcess.InstallIntoProjects[a](InstallerOptions options, Boolean forceTouch, DependenciesFile 
dependenciesFile, LockFile lockFile, FSharpList`1 projectsAndReferences, FSharpMap`2 updatedGroups)
        at Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions 
options)
        at <StartupCode$Paket-Core>.$PublicAPI.Install@266.Invoke(Unit unitVar0)
        at Paket.Utils.RunInLockedAccessMode[a](String lockedFolder, FSharpFunc`2 action)
        at Paket.Program.handleCommand@822-11.Invoke(ParseResults`1 results)
        at Paket.Program.processWithValidationEx$cont@42[a](Boolean silent, FSharpFunc`2 commandF, a result, Unit 
unitVar)
        at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, 
ParseResults`1 result)
        at Paket.Program.handleCommand(Boolean silent, Command command)
        at Paket.Program.main()
```
### Repro steps

Simpliest setup was just
empty folder, 
`paket init`
add nuget dependency for any package
`paket install -v`

But i can't reproduce it on any other computer.

### Known workarounds

Downgrade to paket version 5.171.0. 
Problem starts to appear since version 5.172.1

**Comment by forki** [comment]
That's weird. Do you have some strange path name?

lexarchik <notifications@github.com> schrieb am Mi., 11. Juli 2018, 12:37:

**Comment by lexarchik** [comment]
No, path is `c:\repos\sc`

**Comment by anandasaran** [comment]
I too had the same issue and it is working fine with 5.171.0. Thank you very much @lexarchik.  Will there be any impact if i use 5.174.2 target files with 5.171.0 paket.exe?

**Comment by inosik** [comment]
#3242 (support for the NuGet fallback folder) was added between 5.171.0 and 5.172.1. It looks like Paket crashes while looking for the path of `dotnet.exe` in `PATH` and the current directory. Can you verify that there aren't any funky paths on `PATH` on that machine?

**Comment by lexarchik** [comment]
Yes! I find the problem:) Thank you @inosik 
There is misspelled path in `PATH`: `Cd:\Program Files\nodejs\`. 
DirectoryInfo ctor throws exception on that. 
Maybe Paket should catch that exception and treat it as non-existing directory?

**Comment by forki** [comment]
PR would be very welcome!

lexarchik <notifications@github.com> schrieb am Mi., 11. Juli 2018, 20:59:
