### ISSUE TITLE
Unable to install Paket using PowerShell due to unexpected file path error

### ISSUE THREAD

**Issue by ZenoArrow** [fsprojects/Paket#3306]
Just before I get into this, I apologise in advance for the formatting, I haven't got the hang of formatting code in GitHub issues.

### Description

Have created a PowerShell function to download and setup Paket. However, Paket is throwing an error about file paths being too long, despite the file paths I'm aware of not reaching any Windows limits.

### Repro steps

PowerShell function is as follows (I copied this to the folder "C:\TestReportBuilder\packages\Install-Paket.ps1" on my local machine):

   
    function Install-Paket
        {
        $paketFolder = "$PSScriptRoot\.paket"
        New-Item -Force -ItemType Directory -Path $paketFolder | Out-Null
    
        $paketBootstrapperInstallPath = "$paketFolder\paket.bootstrapper.exe"
        $paketInstallPath = "$paketFolder\paket.exe"

        if (!(Test-Path $paketBootstrapperInstallPath)) {
        
            $github = 'https://github.com'
            $projectname = '/fsprojects/Paket'
            $paketLatestReleaseUrl = $github + $projectname + '/releases/latest'
        
            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
            $latestRelease = Invoke-WebRequest $paketLatestReleaseUrl -Headers @{"Accept"="application/json"} -UseBasicParsing
            $paketLatestVersionPartialUrl = (ConvertFrom-Json $latestRelease.Content).update_url
            $paketLatestVersionPartialUrl = $paketLatestVersionPartialUrl.Replace('/tag','/download')
            $paketExeUrl = $github + $paketLatestVersionPartialUrl + '/paket.bootstrapper.exe'
        
            Write-Host $paketExeUrl
            Write-Host $paketBootstrapperInstallPath

            #System.Net.WebClient used as Invoke-WebRequest doesn't seem to fully work unless IE has been run/configured at least once
            (New-Object System.Net.WebClient).DownloadFile($paketExeUrl, $paketBootstrapperInstallPath)
        
            if(Test-Path $paketBootstrapperInstallPath) {
                Write-Host 'Paket bootstrapper download successful.'
            }
            else {
                Write-Error 'Paket bootstrapper download not successful.'
                return
            }

        }

        else {
            Write-Host 'Paket bootstrapper already available at install path.'
        }

        # Run paket.bootstrapper.exe and paket.exe to finish setup
        & $paketBootstrapperInstallPath

        $paketArgs = @(
            'init'
            '--verbose'
        )

        & $paketInstallPath $paketArgs

    }

### Expected behavior

Would expect paket initialisation to complete without error.

### Actual behavior

    PS C:\Users\thomas.clarke> C:\TestReportBuilder\packages\Install-Paket.ps1

    PS C:\Users\thomas.clarke> Install-Paket
    Paket bootstrapper already available at install path.
    Checking Paket version (downloading latest stable)...
    Paket.exe 5.174.5 is up to date.
    Paket version 5.174.5
    Paket is already initialized in C:\Users\thomas.clarke
    found: C:\Users\thomas.clarke\paket.dependencies
    Parsing C:\Users\thomas.clarke\paket.dependencies
    Performance:
     - Runtime: 5 seconds
    paket.exe : Paket failed with
    At C:\TestReportBuilder\packages\Install-Paket.ps1:46 char:5
    +     & $paketInstallPath $paketArgs
    +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (Paket failed with:String) [], RemoteException
        + FullyQualifiedErrorId : NativeCommandError
     
    -> PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
       StackTrace:
            at System.IO.PathHelper.GetFullPathName()
            at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
            at System.IO.Path.GetFullPathInternal(String path)
            at System.I
    O.FileInfo.Init(String fileName, Boolean checkHost)
            at Paket.ProjectFile.FindCorrespondingFile(FileInfo projectFile, String correspondingFile)
            at Paket.RestoreProcess.findRefFile@155.Invoke(ProjectFile p)
            at Microsoft.FSharp.Collections.ArrayModule.Choose[T,TResult](FSharpFunc`2 chooser, T[] array)
            at Paket.RestoreProcess.findAllReferencesFiles(String root)
            at Paket.PaketEnvModule.fromRootDirectory@48-1.Invoke(FSharpOption`1 _arg2)
            at Chessie.ErrorHandling.Trial.fSuccess@66-11[p,r,q](FSharpFunc`2 f, p x, FSharpList`1 msgs)
            at Chessie.ErrorHandling.Trial.fSuccess@66-11[p,r,q](FSharpFunc`2 f, p x, FSharpList`1 msgs)
            at Paket.Dependencies.Process[c](FSharpFunc`2 f)
            at <StartupCode$Paket-Core>.$PublicAPI.DownloadLatestBootstrapper@440.Invoke(Unit unitVar0)
            at Paket.Utils.RunInLockedAccessMode[a](String lockedFolder, FSharpFunc`2 action)
            at Paket.Program.handleCommand@820-8.Invoke(ParseResults`1 results)
            at Paket.Program.processWithValidationEx$cont@42[a](Boolean silent, FSharpFunc`2 commandF, a result, Unit unitVar)
            at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
            at Paket.Program.handleCommand(Boolean silent, Command command)
            at Paket.Program.main()

### Known workarounds

None that I'm aware of.

**Comment by ZenoArrow** [comment]
Can't replicate issue after restarting Windows. Closing issue.
