### ISSUE TITLE
Parallel access to install-model cache file

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket#3459]
### Description

I noticed an error in the FAKE build process. Apparently we somehow need to re-try or lock access to the cache files:

```
FAKE Process exited with 1:
2018-12-10T12:28:57.3233124Z There was a problem while setting up the environment:
2018-12-10T12:28:57.3290495Z -> One or more errors occurred. (One or more errors occurred. (The process cannot access the file 'C:\Users\VssAdministrator\.nuget\packages\fsharp.core\4.5.4\paket-installmodel.cache' because it is being used by another process.))
2018-12-10T12:28:57.3292742Z -> One or more errors occurred. (The process cannot access the file 'C:\Users\VssAdministrator\.nuget\packages\fsharp.core\4.5.4\paket-installmodel.cache' because it is being used by another process.)
2018-12-10T12:28:57.3292951Z -> IOException: The process cannot access the file 'C:\Users\VssAdministrator\.nuget\packages\fsharp.core\4.5.4\paket-installmodel.cache' because it is being used by another process.
2018-12-10T12:28:57.3293034Z    StackTrace:
2018-12-10T12:28:57.3293088Z         at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
2018-12-10T12:28:57.3293169Z         at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
2018-12-10T12:28:57.3293241Z         at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2018-12-10T12:28:57.3293320Z         at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
2018-12-10T12:28:57.3293406Z         at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
2018-12-10T12:28:57.3293475Z         at System.IO.File.InternalReadAllText(String path, Encoding encoding)
2018-12-10T12:28:57.3293530Z         at System.IO.File.ReadAllText(String path)
2018-12-10T12:28:57.3293602Z         at Paket.NuGet.ofDirectory(String targetFolder)
2018-12-10T12:28:57.3293754Z         at Paket.NuGet.GetContentWithNuSpec@210.Invoke(Unit unitVar)
2018-12-10T12:28:57.3293814Z         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2018-12-10T12:28:57.3293894Z         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2018-12-10T12:28:57.3293951Z         at System.Lazy`1.CreateValue()
2018-12-10T12:28:57.3294085Z         at <StartupCode$Paket-Core>.$DependencyCache.model@250-1.Invoke(Nuspec _arg2)
2018-12-10T12:28:57.3294172Z         at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
2018-12-10T12:28:57.3294244Z         at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
```

https://dev.azure.com/fakebuild/FSProjects/_build/results?buildId=857&view=logs&jobId=fd490c07-0b22-5182-fac9-6d67fe1e939b&taskId=6babf530-62ce-5006-ca3f-7f2244d30f53&lineStart=6710&lineEnd=6743&colStart=30&colEnd=110

### Repro steps

Run paket and fake or multiple fake instances in parallel

### Expected behavior

Works

### Actual behavior

Fails

### Known workarounds

Run the command again

**Comment by matthid** [comment]
Maybe related to https://github.com/fsprojects/Paket/issues/3418
