### ISSUE TITLE
Pushing package No authorization found in config file.

### ISSUE THREAD

**Issue by gggggeorge** [fsprojects/Paket#3624]
Hello,

I try this (which I have done many times before without issue -but now something must have changed...?):

`.paket\paket.exe push ".\nuggets\some_package.1.0.2.nupkg" --url "http://10.2.1.237:9011" --api-key "some_api_key" --verbose`

and I get:

```
Paket version 5.190.0
Pushing package .\nuggets\some_package.1.0.2.nupkg to http://10.2.1.237:9011/api/v2/package - trial 1
No authorization found in config file.
...
Pushing package .\nuggets\some_package.1.0.2.nupkg to http://10.2.1.237:9011/api/v2/package - trial 5
No authorization found in config file.
Performance:
 - Runtime: 6 seconds
Paket failed with
-> WebException: Unable to connect to the remote server
   StackTrace:
        at System.Net.WebClient.OpenWrite(Uri address, String method)
        at Paket.NetUtils.WebClient.UploadFileAsMultipart(WebClient x, Uri url, String filename)
        at Paket.RemoteUpload.push@38(Int32 maxTrials, String url, String apiKey, String clientVersion, String packageFileName, FSharpTypeFunc tracefnVerbose, Boolean useHttpC
lient, Int32 trial)
        at Paket.RemoteUpload.push@38(Int32 maxTrials, String url, String apiKey, String clientVersion, String packageFileName, FSharpTypeFunc tracefnVerbose, Boolean useHttpC
lient, Int32 trial)
        at Paket.RemoteUpload.push@38(Int32 maxTrials, String url, String apiKey, String clientVersion, String packageFileName, FSharpTypeFunc tracefnVerbose, Boolean useHttpC
lient, Int32 trial)
        at Paket.RemoteUpload.push@38(Int32 maxTrials, String url, String apiKey, String clientVersion, String packageFileName, FSharpTypeFunc tracefnVerbose, Boolean useHttpC
lient, Int32 trial)
        at Paket.RemoteUpload.push@38(Int32 maxTrials, String url, String apiKey, String clientVersion, String packageFileName, FSharpTypeFunc tracefnVerbose, Boolean useHttpC
lient, Int32 trial)
        at Paket.RemoteUpload.Push(Int32 maxTrials, String url, String apiKey, String clientVersion, String packageFileName)
        at Paket.Program.handleCommand@837-24.Invoke(ParseResults`1 results)
        at Paket.Program.processWithValidationEx$cont@42[a](Boolean silent, FSharpFunc`2 commandF, a result, Unit unitVar)
        at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
        at Paket.Program.handleCommand(Boolean silent, Command command)
        at Paket.Program.main()
-> SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8888
```

What "config file" is being referred to...?

----
The 10.2.1.237:9011 is a BaGet NuGet server -of which I've uploaded/downloaded many packages without issue, and I can connect to it just fine with Visual Studio NuGet manager.

Thanks,
George Hynes
07/24/2019 5:17pm ET

**Comment by inosik** [comment]
This doesn't seem to be related to authorization, it's just a verbose tracing message.

Looks like some proxy configuration:

> No connection could be made because the target machine actively refused it 127.0.0.1:8888

**Comment by gggggeorge** [comment]
Hi @inosik,

ughhhh, you were right -thanks for pointing me in the right direction!

It turns out I had a fiddler proxy -which after I disabled it, my paket push went through just fine.


Thanks,
George Hynes
07/25/2019 8:32am ET
