### ISSUE TITLE
Unable to find Release output path node in file .csproj for any known platforms

### ISSUE THREAD

**Issue by JohanLarsson** [fsprojects/Paket#3626]
### Description

```
> .\.paket\paket.exe pack publish -v
```

```
Paket version 5.210.0
found: C:\Git\_GuOrg\Gu.Roslyn.Extensions\paket.dependencies
Parsing C:\Git\_GuOrg\Gu.Roslyn.Extensions\paket.dependencies
Loading assembly metadata for C:\Git\_GuOrg\Gu.Roslyn.Extensions\Gu.Roslyn.AnalyzerExtensions\bin\Release\netstandard13\Gu.Roslyn.AnalyzerExtensions.dll
Performance:
 - Runtime: 1 second
.\.paket\paket.exe : Paket failed with
At line:1 char:1
+ .\.paket\paket.exe pack publish -v
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Paket failed with:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
-> Unable to find Release output path node in file C:\Git\_GuOrg\Gu.Roslyn.Extensions\Gu.Roslyn.AnalyzerExtensions\Gu.Roslyn.AnalyzerExtensions.csproj for any known platforms

   StackTrace:

        at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
        at Paket.PackageMetaData.satelliteDlls@279.GenerateNext(IEnumerable`1& next)
        at Microsoft.FSharp.Core.CompilerServices.GeneratedSequence
Base`1.MoveNextImpl()
        at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
        at Paket.PackageMetaData.findDependencies(DependenciesFile dependenciesFile, String config, String platform, TemplateFile template, ProjectFile project, Boolean lockDependencies, Boolean 
minimumFromLockFile, Boolean pinProjectReferences, FSharpOption`1 interprojectReferencesConstraint, FSharpMap`2 projectWithTemplates, Boolean includeReferencedProjects, FSharpOption`1 version, 
PackProcessCache cache)
        at Paket.PackageProcess.allTemplates@217.Invoke(Tuple`2 tupledArg)
        at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
        at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
        at Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@412-1.Invoke(Unit unitVar0)
        at Microsoft.FSharp.Collections.Generator.appG[a](Generator`1 g)
        at Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator`1.System-Collections-IEnumerator-MoveNext()
        at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
        at Paket.PackageProcess.Pack[a](String workingDir, DependenciesFile dependenciesFile, String packageOutputPath, FSharpOption`1 buildConfig, FSharpOption`1 buildPlatform, FSharpOption`1 
version, IEnumerable`1 specificVersions, FSharpOption`1 releaseNotes, FSharpOption`1 templateFile, FSharpOption`1 excludedTemplates, Boolean lockDependencies, Boolean minimumFromLockFile, Boolean 
pinProjectReferences, FSharpOption`1 interprojectReferencesConstraint, Boolean symbols, Boolean includeReferencedProjects, FSharpOption`1 projectUrl)
        at Paket.Program.handleCommand@851-23.Invoke(ParseResults`1 results)
        at Paket.Program.processWithValidationEx$cont@42[a](Boolean silent, FSharpFunc`2 commandF, a result, Unit unitVar)
        at Paket.Program.processWithVa
lidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
        at Paket.Program.handleCommand(Boolean silent, Command command)
        at Paket.Program.main()
```

Repository is [here](https://github.com/GuOrg/Gu.Roslyn.Extensions).
Tried a couple of paket versions but no dice.

The project has packed before and I can't spot anything in the diffs of the project files.

**Comment by baronfel** [comment]
Paket's choking on the non-semver version string that's set on the `Version` property here: https://github.com/GuOrg/Gu.Roslyn.Extensions/blob/master/Gu.Roslyn.Extensions/Gu.Roslyn.Extensions.csproj#L10

As soon as that's made into a proper SemVer version all is well.

**Comment by JohanLarsson** [comment]
Thanks! I'm closing this as by design then. Think it is a regression as it has worked before. Maybe the error message could be more helpful?
