### ISSUE TITLE
Basic EF project example works with dotnet tools but fails with paket

### ISSUE THREAD

**Issue by drk-mtr** [fsprojects/Paket#3652]
### Description

Following the instructions on this page works with dotnet tools (i.e. `dotnet add package`) but fails with `paket`.

### Repro steps

Mostly following steps described here: [Microsoft EF Core documentation](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite)

1. Create new folder, open it and run `dotnet new console`
1. Add package `dotnet add package Microsoft.EntityFrameworkCore.Sqlite`
1. Add package `dotnet add package Microsoft.EntityFrameworkCore.Design`
1. Add a `Model.cs` as described here: [Microsoft EF Core documentation](https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite)
1. Run `dotnet ef migrations add InitialCreate` // Result: successful
1. Run `dotnet ef database update` // Result: db creation / migrations successful
1. Run `paket convert-from-nuget`
1. Make a model change
1. Run `dotnet ef migrations add SecondMig`
1. Run `dotnet ef database update` 

This fails with the message below:

```csharp
System.MissingMethodException: Method not found: 'IntPtr SQLitePCL.sqlite3.get_ptr()'.
   at Microsoft.Data.Sqlite.SqliteConnection.Close()
   at Microsoft.Data.Sqlite.SqliteConnection.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.EntityFrameworkCore.DbContext.Dispose()
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Method not found: 'IntPtr SQLitePCL.sqlite3.get_ptr()'.
```

All package versions at the top of the tree appear to match i.e. both paket and nuget are using:
- `nuget Microsoft.EntityFrameworkCore.Design 2.2.6`
- `nuget Microsoft.EntityFrameworkCore.Sqlite 2.2.6`

### Steps Attempted

I realise that this isn't really the place for troubleshooting dependency tree issues and nuget can be a bit of a black box (hence paket was created!) so apologies for raising the issue here but I wasn't sure where else to go!

I have tried setting `strategy: min`, `lowest_matching: true` and `simplfy: never` but I've had no joy, so I guess my question is: "what steps should I try in order to get paket to follow the same resolution behaviour as nuget package manager?".

**Comment by drk-mtr** [comment]
Worked out this was down to `Microsoft.Data.Sqlite` version. I will learn and not post issues for anything prerelease sorry!

Fix was to use:
`nuget Microsoft.Data.Sqlite prerelease` in `paket.dependencies`
