### ISSUE TITLE
IndexOutOfRangeException starting from 5.231.0

### ISSUE THREAD

**Issue by nikoudel** [fsprojects/Paket#3701]
### Description

paket.exe throws an exception starting from version 5.231.0

### Repro steps

![image](https://user-images.githubusercontent.com/1636683/68283846-fc7db000-0084-11ea-827e-a0e5c6ae467d.png)

**Comment by matthid** [comment]
Can you run with verbose flag to see the stacktrace?

**Comment by nikoudel** [comment]
```Paket failed with
-> IndexOutOfRangeException: Index was outside the bounds of the array.
   StackTrace:
        at Paket.PackageSources.PackageSource.Parse(String line)
        at Paket.Program.discoverPackageSources(FSharpOption`1 explicitSource, FSharpOption`1 dependencies)
        at Paket.Program.findPackageVersions(ParseResults`1 results)
        at Paket.Program.handleCommand@844-18.Invoke(ParseResults`1 results)
        at Paket.Program.processWithValidationEx$cont@42[a](Boolean silent, FSharpFunc`2 commandF, a result, Unit unitVar)
        at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
        at Paket.Program.handleCommand(Boolean silent, Command command)
        at Paket.Program.main()```

**Comment by nikoudel** [comment]
That was quick, thanks!
