### ISSUE TITLE
Error during parsing of paket lock (linux builds)

### ISSUE THREAD

**Issue by Swoorup** [fsprojects/Paket#3926]
### Description

It appears that paket is failing to do a dotnet restore even with latest version

```
18:31:07  Welcome to .NET Core 3.1!
18:31:07  ---------------------
18:31:07  SDK Version: 3.1.403
18:31:15  Tool 'fake-cli' (version '5.20.3') was restored. Available commands: fake
18:31:15  Tool 'paket' (version '5.251.0') was restored. Available commands: paket
18:31:15  
18:31:15  Restore was successful.
18:31:16  Performance:
18:31:16   - Cli parsing: 377 milliseconds
18:31:16   - Packages: 462 milliseconds
18:31:16   - Script analyzing: 241 milliseconds
18:31:16   - Runtime: 1 second
18:31:16  There was a problem while setting up the environment:
[2020-10-30T07:31:16.789Z] -> Error during parsing of '/app/paket.lock'.
[2020-10-30T07:31:16.789Z]    StackTrace:
[2020-10-30T07:31:16.789Z]         at Paket.LockFile.Parse(String lockFileName, String[] lines)
[2020-10-30T07:31:16.789Z]         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
[2020-10-30T07:31:16.789Z]         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
[2020-10-30T07:31:16.789Z]         at System.Lazy`1.CreateValue()
[2020-10-30T07:31:16.789Z]         at Paket.RestoreProcess.Restore$cont@703(Boolean failOnChecks, FileInfo lockFileName, Lazy`1 lockFile, DependenciesFile dependenciesFile, Unit unitVar)
[2020-10-30T07:31:16.789Z]         at Paket.RestoreProcess.Restore(String dependenciesFileName, RestoreProjectOptions projectFile, Boolean force, FSharpOption`1 group, Boolean ignoreChecks, Boolean failOnChecks, FSharpOption`1 targetFrameworks, FSharpOption`1 outputPath, Boolean skipRestoreTargetsExtraction)
[2020-10-30T07:31:16.789Z]         at Paket.Dependencies.Restore()
[2020-10-30T07:31:16.789Z]         at Fake.Runtime.FakeRuntime.paketCachingProvider(FakeConfig config, String cacheDir, Dependencies paketApi, Lazy`1 paketDependenciesFile, FSharpOption`1 group) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 345
[2020-10-30T07:31:16.789Z]         at Fake.Runtime.FakeRuntime.runScript(PrepareInfo preparedScript) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 605
[2020-10-30T07:31:16.789Z]         at Program.runOrBuild(RunArguments args) in D:\a\1\s\src\app\Fake.netcore\Program.fs:line 156
[2020-10-30T07:31:16.789Z] -> failed to parse line '      System.Reflection.Emit.ILGeneration (>= 4.7) - restriction: || (&& (== netcoreapp3.1) (>= net5.0)) (&& (== netcoreapp3.1) (< netcoreapp2.0) (< netstandard2.1)) (&& (== netcoreapp3.1) (< netstandard1.1)) (&& (== netcoreapp3.1) (< netstandard2.0)) (&& (== netcoreapp3.1) (>= uap10.1)) (== netstandard2.0)' (invalid parameter 'net5.0' after >= or < in '>= net5.0)) (&& (== netcoreapp3.1) (< netcoreapp2.0) (< netstandard2.1)) (&& (== netcoreapp3.1) (< netstandard1.1)) (&& (== netcoreapp3.1) (< netstandard2.0)) (&& (== netcoreapp3.1) (>= uap10.1)) (== netstandard2.0)') (Could not parse 'framework: restriction: || (&& (== netcoreapp3.1) (>= net5.0)) (&& (== netcoreapp3.1) (< netcoreapp2.0) (< netstandard2.1)) (&& (== netcoreapp3.1) (< netstandard1.1)) (&& (== netcoreapp3.1) (< netstandard2.0)) (&& (== netcoreapp3.1) (>= uap10.1)) (== netstandard2.0)' as key/value pairs.)
[2020-10-30T07:31:16.789Z]    StackTrace:
[2020-10-30T07:31:16.789Z]         at Paket.LockFileParser.|Remote|NugetPackage|NugetDependency|SourceFile|RepositoryType|Group|InstallOption|$cont@368-6(String line, String matchValue_1, Unit unitVar)
[2020-10-30T07:31:16.789Z]         at Paket.LockFileParser.Parse$cont@456-2(FSharpFunc`2 removeBrackets, String line, FSharpList`1 otherGroups, ParseState currentGroup, Unit unitVar)
[2020-10-30T07:31:16.789Z]         at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 731
[2020-10-30T07:31:16.789Z]         at Paket.LockFile.Parse(String lockFileName, String[] lines)
[2020-10-30T07:31:16.789Z] 	-  invalid parameter 'net5.0' after >= or < in '>= net5.0)) (&& (== netcoreapp3.1) (< netcoreapp2.0) (< netstandard2.1)) (&& (== netcoreapp3.1) (< netstandard1.1)) (&& (== netcoreapp3.1) (< netstandard2.0)) (&& (== netcoreapp3.1) (>= uap10.1)) (== netstandard2.0)'
[2020-10-30T07:31:16.789Z] 	   StackTrace:
[2020-10-30T07:31:16.789Z] 	        at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1639.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1639
[2020-10-30T07:31:16.789Z] 	        at Paket.Requirements.parseOperand@829(Boolean skipSimplify, List`1 problems, String text, FSharpList`1 cur, String next)
[2020-10-30T07:31:16.789Z] 	        at Paket.Requirements.parseOperator@769(Boolean skipSimplify, List`1 problems, String text)
[2020-10-30T07:31:16.789Z] 	        at Paket.Requirements.parseOperand@829(Boolean skipSimplify, List`1 problems, String text, FSharpList`1 cur, String next)
[2020-10-30T07:31:16.789Z] 	        at Paket.Requirements.parseOperator@769(Boolean skipSimplify, List`1 problems, String text)
[2020-10-30T07:31:16.789Z] 	        at Paket.Requirements.parseRestrictionsRaw(Boolean skipSimplify, String text)
[2020-10-30T07:31:16.789Z] 	        at Paket.Requirements.InstallSettings.Parse(Boolean isSimplified, String text)
[2020-10-30T07:31:16.789Z] 	        at Paket.LockFileParser.|Remote|NugetPackage|NugetDependency|SourceFile|RepositoryType|Group|InstallOption|$cont@368-6(String line, String matchValue_1, Unit unitVar)
[2020-10-30T07:31:16.789Z] 	-  Could not parse 'framework: restriction: || (&& (== netcoreapp3.1) (>= net5.0)) (&& (== netcoreapp3.1) (< netcoreapp2.0) (< netstandard2.1)) (&& (== netcoreapp3.1) (< netstandard1.1)) (&& (== netcoreapp3.1) (< netstandard2.0)) (&& (== netcoreapp3.1) (>= uap10.1)) (== netstandard2.0)' as key/value pairs.
[2020-10-30T07:31:16.789Z] 	   StackTrace:
[2020-10-30T07:31:16.789Z] 	        at Paket.Utils.parseKeyValuePairs(String s)
[2020-10-30T07:31:16.789Z] 	        at Paket.Requirements.InstallSettings.Parse(Boolean isSimplified, String text)
[2020-10-30T07:31:16.789Z] 	        at Paket.LockFileParser.|Remote|NugetPackage|NugetDependency|SourceFile|RepositoryType|Group|InstallOption|$cont@368-6(String line, String matchValue_1, Unit unitVar)
[2020-10-30T07:31:16.789Z] 	-> invalid delimiter at position 22
[2020-10-30T07:31:16.789Z] 	   StackTrace:
[2020-10-30T07:31:16.789Z] 	        at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1639.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1639
[2020-10-30T07:31:16.789Z] 	        at Paket.Utils.parseKeyValuePairs(String s)
```

**Comment by forki** [comment]
Can you please upl the dependencies and lock file?

**Comment by Swoorup** [comment]
@forki here you go.
[Archive.zip](https://github.com/fsprojects/Paket/files/5463621/Archive.zip)

**Comment by forki** [comment]
It does restore properly for me with Paket version 5.247.4

the stacktrace shows that this comes from FAKE. I assume your FAKE version comes with outdated internal Paket version.

/cc @matthid

**Comment by matthid** [comment]
Yep use the latest fake beta when you want to use latest paket

**Comment by Swoorup** [comment]
@forki using the same paket files I also get errors like 
```Possible Performance degradation, V3 was not working: One or more errors occurred. (could not get registration data from https://api.nuget.org/v3/registration5-gz-semver2/microsoft.extensions.logging.console/index.json)
``` when using behind a corporate network. Any reasons why? 

Full log: https://paste.ofcode.org/EFsgnP32QcJH8Tiup2YVKm
