### ISSUE TITLE
Build broken since myget roslyn-tools is gone

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket#4002]
In our paket.dependencies we have:

    source https://dotnet.myget.org/F/roslyn-tools/api/v3/index.json
    nuget RoslynTools.MSBuild prerelease

but this seems to be gone. So what now?

**Comment by forki** [comment]
git blame shows @0x53A introduced it. - Hey @0x53A , do you have any ideas?

**Comment by smoothdeveloper** [comment]
trying to remove it in #4003

**Comment by 0x53A** [comment]
``RoslynTools.MSBuild`` was a pre dotnet-sdk way to get a portable msbuild.

If it hasn't already, paket should just move to use the new project format and dotnet-sdk, then it is obsolete and can just be removed.

**Comment by sajagi** [comment]
It still breaks the build on GenerateHelp step as it's used by FAKE.

```
  1) System.TypeInitializationException: The type initializer for '<StartupCode$FakeLib>.$Fake.MSBuildHelper' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\g\paket\packages\build\RoslynTools.MSBuild\tools\msbuild\MSBuild.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.GetAttributes(String path)
   at Fake.MSBuildHelper.exactPathOrBinaryOnPath@77-1.Invoke(String input) in D:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 77
   at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option)
   at <StartupCode$FakeLib>.$Fake.MSBuildHelper..cctor() in D:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 116
   --- End of inner exception stack trace ---
   at Fake.MSBuildHelper.get_msBuildExe()
   at FSI_0005.Build.fakeStartInfo(String fsiargs, String script, String workingDirectory, String args, IEnumerable`1 environmentVars, ProcessStartInfo info)
   at FSI_0005.Build.generateHelp'@552-2.Invoke(ProcessStartInfo info)
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in D:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 83
   at FSI_0005.Build.executeWithOutput(FSharpFunc`2 configStartInfo)
   at FSI_0005.Build.execute@521.Invoke(FSharpFunc`2 configStartInfo)
   at FSI_0005.Build.executeHelper[a](FSharpFunc`2 executer, Boolean fail, String traceMsg, String failMessage, a configStartInfo)
   at FSI_0005.Build.execute@521-1.Invoke(Boolean fail, String traceMsg, String failMessage, FSharpFunc`2 configStartInfo)
   at FSI_0005.Build.generateHelp'(Boolean commands, Boolean fail, Boolean debug)
   at FSI_0005.Build.clo@559-60.Invoke(Unit _arg1)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
```

I guess the lucky ones have MSBuild environment variable set or similar so they don't see this.

**Comment by sajagi** [comment]
That said, there are few more issues:
- MSBuild 18 (2026) paths are not supported 
- `dotnet msbuild` alternative is not considered. 

On the other hand, it's probably not even needed as  it's only passed to be used in generate.fsx, but it seems to be working just fine without it. 

Happy to provide a (one-line) PR removing MSBuild env var in `fakeStartInfo` if you think that's the way to go.
