### ISSUE TITLE
Running "paket install" results in "ArgumentException: Illegal characters in path."

### ISSUE THREAD

**Issue by older** [fsprojects/Paket#4004]
### Description

Running "paket install" produces the following error:

    Paket failed with
    -> ArgumentException: Illegal characters in path.

### Repro steps

I can only reproduce it in one of my repositories which is pretty big one (over 200 projects), but it happens on 2 different machines. 

### Expected behavior

Maybe better error message, which includes invalid path in question? Right now I have no way to find out why it is failing and what exactly I need to fix. 

### Actual behavior

Here's full stacktrace reported when I run it with "--verbose":
```
Paket failed with
-> ArgumentException: Illegal characters in path.
   StackTrace:
        at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
        at System.IO.Path.InternalGetDirectoryName(String path)
        at Paket.NuGet.ofDirectory@155.Invoke(String di)
        at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
        at Paket.NuGet.ofDirectory$cont@134(String targetFolder, String spec, Unit unitVar)
        at Paket.NuGet.GetContentWithNuSpec@224.Invoke(Unit unitVar)
        at System.Lazy`1.CreateValue()
        at System.Lazy`1.LazyInitValue()
        at System.Lazy`1.CreateValue()
        at System.Lazy`1.LazyInitValue()
        at Paket.RestoreProcess.CreateInstallModel@248-1.Invoke(Tuple`2 _arg1)
        at Microsoft.FSharp.Control.AsyncBuilderImpl.args@506-1.Invoke(a a)
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
        at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
        at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
        at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
        at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
        at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
        at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
        at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
        at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
        at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
        at Paket.InstallProcess.InstallIntoProjects[a](InstallerOptions options, Boolean forceTouch, DependenciesFile dependenciesFile, LockFile lockFile, FSharpList`1 projectsAndReferences, FSharpMap`2 updatedGroups)
        at Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions options)
        at <StartupCode$Paket-Core>.$PublicAPI.Install@266.Invoke(Unit unitVar0)
        at Paket.Utils.RunInLockedAccessMode[a](String lockedFolder, FSharpFunc`2 action)
        at Paket.Program.handleCommand@840-11.Invoke(ParseResults`1 results)
        at Paket.Program.processWithValidationEx$cont@42[a](Boolean silent, FSharpFunc`2 commandF, a result, Unit unitVar)
        at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result)
        at Paket.Program.handleCommand(Boolean silent, Command command)
        at Paket.Program.main()
```

**Comment by sven-s** [comment]
I have the same problem. As a workaround I use paket restore.
