### ISSUE TITLE
paket update can't get nuget dependencies with an "." inside the name

### ISSUE THREAD

**Issue by jolessops** [fsprojects/Paket#4136]
### Description

In some NuGet package names, we included the version we are currently building to be sure that the project only takes its version dependencies.

nuget net-project-v1-test

In the case we need the create a patch inside this version, the name will contain a period

nuget net-project-v1.1-test

When the main project is doing a paket update to get every package dependencies he needs, Paket update makes an error on the package with "." even if the package is inside the local source.

**The error**

> Please check the feed definition in your paket.dependencies file.
>      at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message)
>      at Paket.NuGetLocal.getDetailsFromLocalNuGetPackage@63.Invoke(Unit unitVar)
>      at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
>      at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
>   Something failed in GetPackageDetails, trying again with force: Couldn't get package details for package net-project-v1.1-test 36.3.65500 on \PackageSource.
>   Source \PackageSource' exception: System.Exception: The package net-project-v1.1-test 36.3.65500 can't be found in \PackageSource.
>   Please check the feed definition in your paket.dependencies file.
>      at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message)
>      at Paket.NuGetLocal.getDetailsFromLocalNuGetPackage@63.Invoke(Unit unitVar)
>      at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
>      at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@577.Invoke(AsyncActivation`1 ctxt)
>      at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
>       Package not available.
>         Message: Unable to retrieve package details for 'net-project-v1.1-test'-36.3.65500
>   Resolution finished, but some errors were encountered:
>   -> Unable to retrieve package details for 'net-project-v1.1-test'-36.3.65500
>   -> Couldn't get package details for package net-project-v1.1-test 36.3.65500 on 
> 

### Repro steps

1. Having a project with dependencies that contain a "." inside the package name
2. Build the package with a "." inside the name and copy this package inside a local directory
3. Be sure that the paket.dependencies file have the local directory as a source
4. Before building the project that is inside another directory, make a paket update so paket will get the dependencies
5. Same error should be happening

### Expected behavior

paket should be able to get package with a "." inside the name

### Known workarounds

Remove the "." inside the package name

**Comment by forki** [comment]
Did this work with older versions of Paket? Which version do you use?

jolessops ***@***.***> schrieb am Di., 29. März 2022, 21:55:

**Comment by jolessops** [comment]
Currently using version 6.1.3 but we made the test with the latest 7.1.2 and an older version I think 5.2 and they both did not work.

> Did this work with older versions of Paket? Which version do you use? jolessops ***@***.***> schrieb am Di., 29. März 2022, 21:55:
