### ISSUE TITLE
Request to 'https://api.nuget.org/v3/index.json' failed with unknown error (_safeGetFromUrl)

### ISSUE THREAD

**Issue by 64J0** [fsprojects/Paket#4259]
### Description

Hi, hope you're good. I'm having some consistent problems with the commands `dotnet paket install` and `dotnet paket update` at my Ubuntu 22.04 environment. When using a Docker container with ubuntu-22.04 image, it works fine.

I'm not sure how to keep debugging this problem. Already compared my `/etc/ssl/openssl.cnf` configuration between my local environment and what we have by default on ubuntu-22.04 container.

I tested with paket versions: 8.0.3, 7.2.1, 7.0.0.

If anyone has a tip to keep debugging, or knows a workaround, please let me know.

### Repro steps

Use either:

- `dotnet paket install`, or
- `dotnet paket update`

### Expected behavior

Update `paket.lock`.

### Actual behavior

When using the `--verbose` flag, I get this log:

```bash
Total time taken: 446 milliseconds
 - Resolver: 304 milliseconds (1 runs)
    - Runtime: 93 milliseconds
    - Blocked (retrieving package versions): 210 milliseconds (1 times)
 - Average Request Time: 35 milliseconds
 - Number of Requests: 4
 - Runtime: 780 milliseconds
Paket failed with
-> Unable to retrieve package versions for 'Microsoft.NET.Test.Sdk'
   -- CLOSED --
      
   -- OPEN ----
      ...
   StackTrace:
        at Paket.PackageResolver.getVersionsBlock@1075-1.GenerateNext(IEnumerable`1& next) in D:\code\Paket\src\Paket.Core\Dependencies\PackageResolver.fs:line 1087
        at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 405
        at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 441
        at Microsoft.FSharp.Collections.SeqModule.oneStepTo@989[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 1005
        at Microsoft.FSharp.Collections.SeqModule.action@4793-1[T](IEnumerable`1 source, List`1 prefix, Int32 i, FSharpRef`1 enumeratorR, Unit unitVar0) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 1022
        at Microsoft.FSharp.Collections.SeqModule.result@1013.Invoke(Int32 i) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 1017
        at Microsoft.FSharp.Collections.Internal.IEnumerator.unfold@205.DoMoveNext(b& curr) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 207
        at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 64
        at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 77
        at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 64
        at Microsoft.FSharp.Collections.Internal.IEnumerator.next@193[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 195
        at Microsoft.FSharp.Collections.Internal.IEnumerator.filter@188.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 196
        at Microsoft.FSharp.Collections.SeqModule.IsEmpty[T](IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 702
        at Paket.PackageResolver.getCompatibleVersions(ResolverStep currentStep, GroupName groupName, PackageRequirement currentRequirement, IDictionary`2 rootDependencies, FSharpFunc`2 getVersionsF, Boolean globalOverride, FSharpOption`1 globalStrategyForDirectDependencies, FSharpOption`1 globalStrategyForTransitives) in D:\code\Paket\src\Paket.Core\Dependencies\PackageResolver.fs:line 601
        at Paket.PackageResolver.step@1131(UpdateMode updateMode, GroupName groupName, FSharpOption`1 globalStrategyForTransitives, FSharpOption`1 globalStrategyForDirectDependencies, FrameworkRestrictions globalFrameworkRestrictions, FSharpFunc`2 getVersionsRaw, FSharpFunc`2 getPreferredVersionsRaw, FSharpFunc`2 getPackageDetailsRaw, FSharpSet`1 cliToolSettings, ResolverRequestQueue workerQueue, Int32 taskTimeout, TimeSpan loopTimeout, ConcurrentDictionary`2 startedGetPackageDetailsRequests, FSharpFunc`2 getPackageDetailsBlock, ConcurrentDictionary`2 startedGetVersionsRequests, FSharpOption`1 packageFilter, IDictionary`2 rootDependenciesDict, FSharpSet`1 lockedPackages, DateTime loopTime, Stage stage, StackPack stackpack, IEnumerable`1 compatibleVersions, StepFlags flags) in D:\code\Paket\src\Paket.Core\Dependencies\PackageResolver.fs:line 1208
        at Paket.PackageResolver.tryStep@1446(UpdateMode updateMode, GroupName groupName, FSharpOption`1 globalStrategyForTransitives, FSharpOption`1 globalStrategyForDirectDependencies, FrameworkRestrictions globalFrameworkRestrictions, FSharpFunc`2 getVersionsRaw, FSharpFunc`2 getPreferredVersionsRaw, FSharpFunc`2 getPackageDetailsRaw, FSharpSet`1 cliToolSettings, ResolverRequestQueue workerQueue, Int32 taskTimeout, TimeSpan loopTimeout, ConcurrentDictionary`2 startedGetPackageDetailsRequests, FSharpFunc`2 getPackageDetailsBlock, ConcurrentDictionary`2 startedGetVersionsRequests, FSharpOption`1 packageFilter, IDictionary`2 rootDependenciesDict, FSharpSet`1 lockedPackages, DateTime loopTime, StepResult result) in D:\code\Paket\src\Paket.Core\Dependencies\PackageResolver.fs:line 1450
        at Paket.PackageResolver.Resolve(FSharpFunc`2 getVersionsRaw, FSharpFunc`2 getPreferredVersionsRaw, FSharpFunc`2 getPackageDetailsRaw, GroupName groupName, FSharpOption`1 globalStrategyForDirectDependencies, FSharpOption`1 globalStrategyForTransitives, FrameworkRestrictions globalFrameworkRestrictions, FSharpSet`1 rootDependencies, UpdateMode updateMode) in D:\code\Paket\src\Paket.Core\Dependencies\PackageResolver.fs:line 1461
        at <StartupCode$Paket-Core>.$DependenciesFile.resolveGroup@220-1.Invoke(GroupName groupName, b _arg1) in D:\code\Paket\src\Paket.Core\PaketConfigFiles\DependenciesFile.fs:line 301
        at Microsoft.FSharp.Collections.MapTreeModule.mapiOpt[TKey,TValue,TResult](FSharpFunc`3 f, MapTree`2 m) in D:\a\_work\1\s\src\fsharp\FSharp.Core\map.fs:line 360
        at Microsoft.FSharp.Collections.MapModule.Map[TKey,T,TResult](FSharpFunc`2 mapping, FSharpMap`2 table) in D:\a\_work\1\s\src\fsharp\FSharp.Core\map.fs:line 953
        at Paket.UpdateProcess.selectiveUpdate(Boolean force, FSharpFunc`2 getSha1, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, FSharpFunc`2 getRuntimeGraphFromPackage, LockFile lockFile, DependenciesFile dependenciesFile, UpdateMode updateMode, SemVerUpdateMode semVerUpdateMode) in D:\code\Paket\src\Paket.Core\Installation\UpdateProcess.fs:line 153
        at Paket.UpdateProcess.SelectiveUpdate(DependenciesFile dependenciesFile, FSharpOption`1 alternativeProjectRoot, UpdateMode updateMode, SemVerUpdateMode semVerUpdateMode, Boolean force) in D:\code\Paket\src\Paket.Core\Installation\UpdateProcess.fs:line 220
        at Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions options) in D:\code\Paket\src\Paket.Core\Installation\UpdateProcess.fs:line 280
        at Paket.UpdateProcess.Update(String dependenciesFileName, UpdaterOptions options) in D:\code\Paket\src\Paket.Core\Installation\UpdateProcess.fs:line 370
        at <StartupCode$Paket-Core>.$PublicAPI.Update@323.Invoke(Unit unitVar0) in D:\code\Paket\src\Paket.Core\PublicAPI.fs:line 324
        at Paket.Utils.RunInLockedAccessMode(String lockedFolder, FSharpFunc`2 lockedAction) in D:\code\Paket\src\Paket.Core\Common\Utils.fs:line 540
        at Paket.Dependencies.Update(Boolean force, Boolean withBindingRedirects, Boolean cleanBindingRedirects, Boolean createNewBindingFiles, Boolean installAfter, SemVerUpdateMode semVerUpdateMode, Boolean touchAffectedRefs) in D:\code\Paket\src\Paket.Core\PublicAPI.fs:line 321
        at Paket.Program.update(ParseResults`1 results) in D:\code\Paket\src\Paket\Program.fs:line 509
        at Paket.Program.handleCommand@888-16.Invoke(ParseResults`1 results)
        at Paket.Program.processWithValidationEx[a](FSharpFunc`2 printUsage, Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, a result) in D:\code\Paket\src\Paket\Program.fs:line 47
        at Paket.Program.processWithValidation[T](Boolean silent, FSharpFunc`2 validateF, FSharpFunc`2 commandF, ParseResults`1 result) in D:\code\Paket\src\Paket\Program.fs:line 129
        at Paket.Program.processCommand[a](Boolean silent, FSharpFunc`2 commandF, ParseResults`1 result) in D:\code\Paket\src\Paket\Program.fs:line 132
        at Paket.Program.handleCommand(Boolean silent, Command command) in D:\code\Paket\src\Paket\Program.fs:line 888
        at Paket.Program.main() in D:\code\Paket\src\Paket\Program.fs:line 980
-> Could not load resources from 'https://api.nuget.org/v3/index.json'
-> Request to 'https://api.nuget.org/v3/index.json' failed with unknown error (_safeGetFromUrl)
-> HttpRequestException: The SSL connection could not be established, see inner exception.
-> AuthenticationException: Authentication failed, see inner exception.
-> TypeInitializationException: The type initializer for 'SslMethods' threw an exception.
-> TypeInitializationException: The type initializer for 'Ssl' threw an exception.
-> TypeInitializationException: The type initializer for 'SslInitializer' threw an exception.
-> OpenSslCryptographicException: error:0E076071:configuration file routines:module_run:unknown module name
```

When I try using `curl https://api.nuget.org/v3/index.json`, it works fine.

### Known workarounds

-

**Comment by 64J0** [comment]
The `dotnet paket install` command worked after I removed the cache with `dotnet paket clear-cache`.

**Comment by 64J0** [comment]
The trick mentioned before is not working today
