### ISSUE TITLE
Paket.Core can't find Ionic

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#685]
I'm using Paket.Core through a standalone .fsx file in my solution. If I do a paket update from the command line, it works fine. However if I try the same through Paket.Core via ``dependencies.Update()``, I get the following: -

	System.IO.FileNotFoundException: Could not load file or assembly 'Ionic.Zip, Version=1.9.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
	File name: 'Ionic.Zip, Version=1.9.3.0, Culture=neutral, PublicKeyToken=null'
	   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
	   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
	   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
	   at Paket.InstallProcess.createModel(String root, FSharpList`1 sources, Boolean force, LockFile lockFile)
	   at Paket.InstallProcess.InstallIntoProjects(FSharpList`1 sources, Boolean force, Boolean hard, Boolean withBindingRedirects, LockFile lockFile, IEnumerable`1 projects)
	   at Paket.UpdateProcess.SmartInstall(String dependenciesFileName, FSharpOption`1 exclude, Boolean force, Boolean hard, Boolean withBindingRedirects)
	   at <StartupCode$Paket-Core>.$PublicAPI.UpdatePackage@163.Invoke(Unit unitVar0)
	   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
	   at <StartupCode$FSI_0006>.$FSI_0006.main@()

My code has no dependency on Ionic and it's not in the lock file.

**Comment by forki** [comment]
IIRC that's the zip lib that paket uses. It should be in the packages folder and you can  #r it.

**Comment by isaacabraham** [comment]
Fixed it, cheers.
