### ISSUE TITLE
Wrong version binding redirect is generated when referencing a PCL dependency that uses System.Xml.Linq

### ISSUE THREAD

**Issue by reijerh** [fsprojects/Paket#703]
**To reproduce:**
Create a .NET 4.5 (WPF?) project with:

_paket.dependencies:_
```
redirects: on
framework: net45
source https://www.nuget.org/api/v2
```
_paket.references:_
`FluentAssertions`

This will result in _app.config_ binding redirects:
```
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="FluentAssertions.Core" publicKeyToken="33f2691a05b67b6a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-3.3.0.0" newVersion="3.3.0.0" />
  </dependentAssembly>
  <dependentAssembly>
    <assemblyIdentity name="FluentAssertions" publicKeyToken="33f2691a05b67b6a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-3.3.0.0" newVersion="3.3.0.0" />
  </dependentAssembly>
  <dependentAssembly>
    <assemblyIdentity name="Microsoft.CSharp" publicKeyToken="31bf3856ad364e35" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-5.0.5.0" newVersion="5.0.5.0" />
  </dependentAssembly>
  <dependentAssembly>
    <assemblyIdentity name="Microsoft.VisualStudio.QualityTools.UnitTesting.Silverlight" publicKeyToken="31bf3856ad364e35" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-2.0.5.0" newVersion="2.0.5.0" />
  </dependentAssembly>
  <dependentAssembly>
    <assemblyIdentity name="System.Xml.Linq" publicKeyToken="31bf3856ad364e35" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-5.0.5.0" newVersion="5.0.5.0" />
  </dependentAssembly>
</assemblyBinding>
```

**The problem is that for _Microsoft.CSharp_ and _System.Xml.Linq_ it redirects to _5.0.5.0_, while it should redirect to _4.0.0.0_. The 5.0 versions seem to be Silverlight versions according to Google.** It also probably shouldn't add a redirect for _Microsoft.VisualStudio.QualityTools.UnitTesting.Silverlight_ at all.

When you now add another package that references an older version of these DLLs, e.g. _Kent.Boogaart.Converters_, the application will crash with an exception like:
```
{System.TypeInitializationException: The type initializer for 'Kent.Boogaart.HelperTrinity.ExceptionHelper' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Xml.Linq, Version=5.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Xml.Linq, Version=2.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.
   --- End of inner exception stack trace ---
   at Kent.Boogaart.HelperTrinity.ExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Kent.Boogaart.HelperTrinity.ExceptionHelper..ctor(Type forType)
   at Kent.Boogaart.Converters.ExpressionConverter..cctor()}
```

Just FYI, this is in _FluentAssertions.nuspec_:
```
<frameworkAssemblies>
  <frameworkAssembly assemblyName="System.Xml" targetFramework="" />
  <frameworkAssembly assemblyName="System.Xml.Linq" targetFramework="" />
</frameworkAssemblies>
```

**Comment by isaacabraham** [comment]
Fairly sure that this is related to #711 i.e. we're reading during binding redirects generation for dependencies that aren't appropriate for the selected framework.

**Comment by reijerh** [comment]
Is this caused by FluentAssertions's packaging configuration? (i.e: should I create an issue at their repo?)
