### ISSUE TITLE
Failing convert from nuget with exception

### ISSUE THREAD

**Issue by Stift** [fsprojects/Paket#830]
When I convert a solution I get the following exception:

```
...
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at <StartupCode$Paket-Core>.$ProjectFile.RemoveImportAndTargetEntries@493.Invoke(XmlNode node)
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at Paket.NuGetConvert.convertProjects@325.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.NuGetConvert.createPaketEnv@334.Invoke(DependenciesFile _arg1)
   at Chessie.ErrorHandling.Trial.fSuccess@63-11[p,r,q](FSharpFunc`2 f, p x, FSharpList`1 msgs)
   at Paket.NuGetConvert.createResult(DirectoryInfo rootDirectory, NugetEnv nugetEnv, CredsMigrationMode credsMirationMode)
   at Chessie.ErrorHandling.Trial.fSuccess@63-11[p,r,q](FSharpFunc`2 f, p x, FSharpList`1 msgs)
   at Chessie.ErrorHandling.Trial.fSuccess@63-11[p,r,q](FSharpFunc`2 f, p x, FSharpList`1 msgs)
   at Chessie.ErrorHandling.Trial.fSuccess@63-11[p,r,q](FSharpFunc`2 f, p x, FSharpList`1 msgs)
   at <StartupCode$Paket-Core>.$PublicAPI.ConvertFromNuget@66.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Program.clo@255-11.Invoke(ArgParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   at Paket.Program.processCommand@71-1.Invoke(Command command, String[] args)
   at <StartupCode$paket>.$Paket.Program.main@()
```

**Comment by forki** [comment]
woupsi. NPE - I love them.

can you please try to debug this (or create a repro). I assume it's in createPaketEnv.
debugging should be easy. clone the repo, set Paket.exe as startup project. Set working dir to your solution path and put "convert-from-nuget" in the command line arg.

/cc @theimowski

**Comment by Stift** [comment]
Will do in the late afternoon when I have time. Just wanted to let you know early.

**Comment by forki** [comment]
thanks. Unfortunately can't see the issue without further data. ;-)

2015-05-20 15:27 GMT+02:00 Christian <notifications@github.com>:

**Comment by theimowski** [comment]
I'll have a look - maybe can predict what went wrong

**Comment by Stift** [comment]
I've got the error. I will provide a fix today. Just have to write some unit tests for this. I think I can provide a pull request this evening

**Comment by Stift** [comment]
Oh @theimowski was faster. Then I only provide some unit tests...

**Comment by forki** [comment]
Yeah this guy is amazing ;-)

**Comment by theimowski** [comment]
:triumph:

**Comment by Stift** [comment]
absolutely admit :cake:
