### ISSUE TITLE
Paket crashes with Null Ref Exception for MBrace

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket#923]
Having a paket.dependencies file with:

```
source https://www.nuget.org/api/v2
nuget MBrace.Azure -pre
```

Causes the following NRE and full crash with paket 1.19.0.0 (full crash = windows crash dialog appears).

```
λ .paket\paket install
Resolving packages:
 - MBrace.Azure 0.6.10-alpha

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Paket.utils.zipOpt[a,b](FSharpList`1 l1, FSharpList`1 l2)
   at Paket.PreRelease.System-IComparable-CompareTo(Object yobj)
   at Paket.VersionRequirement.CompareTo(Object obj, IComparer comp)
   at Microsoft.FSharp.Collections.SetTreeModule.mem[T](IComparer`1 comparer, T k, SetTree`1 t)
   at Paket.Requirements.optimizeRestrictions@88.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.NuGetV2.GetPackageDetails(String root, Boolean force, FSharpList`1 sources, PackageName packageName, SemVerInfo version)
   at <StartupCode$Paket-Core>.$DependenciesFile.Resolve@314-3.Invoke(FSharpList`1 sources, PackageName packageName, SemVerInfo version)
   at Paket.PackageResolver.getExploredPackage@155(FSharpList`1 globalFrameworkRestrictions, FSharpFunc`2 getPackageDetailsF, Dictionary`2 exploredPackages, PackageRequirement dependency, SemVerInfo version)
   at Paket.PackageResolver.tryToImprove@298-2.Invoke(SemVerInfo versionToExplore)
   at Microsoft.FSharp.Collections.ListModule.loop@142-20[T,TState](FSharpFunc`3 f, TState s, FSharpList`1 xs)
   at Paket.PackageResolver.step@199(FSharpList`1 globalFrameworkRestrictions, FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, Dictionary`2 exploredPackages, Dictionary`2 allVersions, Dictionary`2 conflictHistory, FSharpMap`2 filteredVersions, FSharpList`1 selectedPackageVersions, FSharpSet`1 closedRequirements, FSharpSet`1 openRequirements)
   at Paket.PackageResolver.Resolve(FSharpFunc`2 getVersionsF, FSharpFunc`2 getPackageDetailsF, FSharpList`1 globalFrameworkRestrictions, FSharpList`1 rootDependencies)
   at Paket.DependenciesFile.Resolve(FSharpFunc`2 getSha1, FSharpFunc`2 getVersionF, FSharpFunc`2 getPackageDetailsF)
   at Paket.UpdateProcess.SelectiveUpdate(DependenciesFile dependenciesFile, Boolean updateAll, FSharpOption`1 exclude, Boolean force)
   at Paket.UpdateProcess.SmartInstall(String dependenciesFileName, Boolean updateAll, FSharpOption`1 exclude, UpdaterOptions options)
   at <StartupCode$Paket-Core>.$PublicAPI.Install@156.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Program.handler@280-10.Invoke(ArgParseResults`1 results)
   at Paket.Program.processWithValidation[T](FSharpFunc`2 validateF, FSharpFunc`2 commandF, Command command, String[] args)
   at Paket.Program.processCommand@71-1.Invoke(Command command, String[] args)
   at Paket.Program.main()
   at <StartupCode$paket>.$Paket.Program.main@()
```

**Comment by baronfel** [comment]
my bad! I'm working on a fix right now.

**Comment by isaacabraham** [comment]
ok cool. this also affects update as well.

**Comment by baronfel** [comment]
i couldn't find an implementation of 'zip two lists of differing sizes with None extending the shorter one' when I was implementing this.  Any ideas where to find one, instead of relying on my hand-rolled implementation?

**Comment by isaacabraham** [comment]
can you post a link to the code in paket where you're doing this?

**Comment by baronfel** [comment]
https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/SemVer.fs#L6

prereleases are compared segment by segment, and if one set of segments is longer than the other, the longer list is greater.

**Comment by baronfel** [comment]
very odd. I can't seem to repro on my end, Isaac. I'm able to both install and update given the spec you provide.

**Comment by forki** [comment]
I can reproduce.

**Comment by isaacabraham** [comment]
Hmmm. Why do we have some people with different outputs here.

**Comment by isaacabraham** [comment]
And where is the NRE occurring?

**Comment by baronfel** [comment]
it's somewhere in the zipopt function, but I haven't been able to make that fail in some local testing I've been doing just now.

**Comment by forki** [comment]
I think it's outside of zipopt.

**Comment by forki** [comment]
this is really weird. I can't reproduce after update -f.

I added a bit of null checks anyway. Does it help?

**Comment by baronfel** [comment]
yeah, that's about as far as I got in my tests too.  Quite odd all around.

**Comment by forki** [comment]
yeah after thinking about it. 
The error is probably that we didn't increased the cache format version (JSON file format)

will do that now.
