### ISSUE TITLE
method not found

### ISSUE THREAD

**Issue by MorganPersson** [fsprojects/Paket#990]
I just forked Paket and when I run build.cmd I get:
`Starting Target: GenerateHelp (==> CleanDocs)
C:\code\github\Paket\docs\content\release-notes.md does not exist.
C:\code\github\Paket\docs\content\license.md does not exist.
System.MissingMethodException: Method not found: 'Nessos.UnionArgParser.UnionArgParser`1<!!0> Nessos.UnionArgParser.UnionArgParser.Create(Microsoft.FSharp.Core.FSharpOption`1<System.String>)'.
   at Paket.Commands.getSyntax@324(Command command, Command _arg1)
   at Paket.Commands.markdown(Command command, String additionalText) in C:\code\github\Paket\src\Paket\Commands.fs:line 350
   at FSI_0001.f@1(Command command) in C:\code\github\Paket\docs\tools\generate.fsx:line 17
   at <StartupCode$FSI_0001>.$FSI_0001.main@() in C:\code\github\Paket\docs\tools\generate.fsx:line 9`

Is there some ore-requisite I'm missing on my machine?

**Comment by forki** [comment]
Mhm I assume there is still something fucky with the latest
unionargsparser. There were breaking changes.

**Comment by eiriktsarpalis** [comment]
Ah, yes. The latest version has moved to F# 3.1 so a binding redirect is necessary if using from F# 3.0 environments.

See also [this discussion](https://github.com/nessos/UnionArgParser/pull/37).

**Comment by forki** [comment]
does this still happen?

**Comment by MorganPersson** [comment]
yes :-(

**Comment by forki** [comment]
This is only in the GenerateDocs target? Apart from that Paket runs fine?
That's so strange.

**Comment by MorganPersson** [comment]
`.\build.cmd RunTests` works fine.

**Comment by sideeffffect** [comment]
`.\build.cmd RunTests` works fine for me too.

`.\build.cmd` however fails with ``System.MissingMethodException: Method not found: 'Nessos.Argu.ArgumentParser`1<!!0> Nessos.Argu.ArgumentParser.Create(Microsoft.FSharp.Core.FSharpOption`1<System.String>)'.``

```
Starting Target: GenerateHelp (==> CleanDocs)
Deleting c:\Users\pelechon\Projects\Paket\docs\content\release-notes.md
Deleting c:\Users\pelechon\Projects\Paket\docs\content\license.md
System.MissingMethodException: Method not found: 'Nessos.Argu.ArgumentParser`1<!!0> Nessos.Argu.ArgumentParser.Create(Mi
crosoft.FSharp.Core.FSharpOption`1<System.String>)'.
   at Paket.Commands.getSyntax@340(Command command, Command _arg1)
   at Paket.Commands.markdown(Command command, String additionalText) in c:\Users\pelechon\Projects\Paket\src\Paket\Comm
ands.fs:line 366
   at FSI_0001.f@1(Command command) in c:\Users\pelechon\Projects\Paket\docs\tools\generate.fsx:line 17
   at <StartupCode$FSI_0001>.$FSI_0001.main@() in c:\Users\pelechon\Projects\Paket\docs\tools\generate.fsx:line 9
Stopped due to error
Running build failed.
Error:
System.Exception: generating help documentation failed
   at FSI_0001.Build.generateHelp'(Boolean commands, Boolean fail, Boolean debug)
   at FSI_0001.Build.clo@299-32.Invoke(Unit _arg1)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 48
3

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target            Duration
------            --------
Clean             00:00:00.0075401
AssemblyInfo      00:00:00.0359472
Build             00:00:10.3809351
BuildPowerShell   00:00:02.0479623
RunTests          00:00:06.9741778
CleanDocs         00:00:00.0009307
Total:            00:00:21.1624929
Status:           Failure
---------------------------------------------------------------------
  1) System.Exception: generating help documentation failed
   at FSI_0001.Build.generateHelp'(Boolean commands, Boolean fail, Boolean debug)
   at FSI_0001.Build.clo@299-32.Invoke(Unit _arg1)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 48
3
---------------------------------------------------------------------
```

**Comment by forki** [comment]
Sounds like FSharp.Formatting uses wrong FSharp.Core.dll on your machine.
/cc @tpetricek

**Comment by sideeffffect** [comment]
So how do I make it use the right dll?

**Comment by forki** [comment]
not sure. for now I recommend to exclude that build target
